import { chromium } from 'playwright';
import { createServer } from 'vite';
import { mkdir, readFile } from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {triangleGlb} from './model-fixture.mjs';
import assert from 'node:assert/strict';
const server = await createServer({ server: { host: '127.0.0.1', port: 0 } });
let browser;
try {
  await server.listen();
  const address = server.httpServer.address();
  browser = await chromium.launch({ channel: 'chrome', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(`http://127.0.0.1:${address.port}`);
  await page.getByRole('heading', { name: 'Your first scenario starts here' }).waitFor();
  await mkdir('Artifacts', { recursive: true });
  await page.screenshot({ path: 'Artifacts/empty-desktop.png', fullPage: true });
  await page.getByLabel('Project title').fill('Client site induction');
  await page.getByLabel('Environment template').selectOption('Site');
  await page.getByRole('button', { name: 'Create empty project' }).click();
  await page.getByRole('heading', { name: 'Client site induction' }).waitFor();
  await page.reload();
  await page.getByRole('heading', { name: 'Client site induction' }).waitFor();
  const event = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export draft' }).click();
  const download = await event;
  const draft = JSON.parse(await readFile(await download.path(), 'utf8'));
  assert.equal(draft.title, 'Client site induction');
  assert.deepEqual(draft.assets, []);
  assert.deepEqual(draft.targets, ['webxr', 'unity']);
  await page.getByLabel('Open draft', { exact: true }).setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{"schemaVersion":99}') });
  await page.getByRole('status').filter({ hasText: 'Unexpected or missing' }).waitFor();
  await page.getByRole('heading', { name: 'Client site induction' }).waitFor();
  const imported = { ...draft, title: 'Imported draft' };
  await page.getByLabel('Open draft', { exact: true }).setInputFiles({ name: 'valid.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(imported)) });
  await page.getByRole('heading', { name: 'Imported draft' }).waitFor();
  await page.screenshot({ path: 'Artifacts/project-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 375, height: 812 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth), false);
  await page.screenshot({ path: 'Artifacts/project-phone.png', fullPage: true });
  await page.evaluate(() => localStorage.clear());
  await page.reload();
  await page.getByRole('heading', { name: 'Your first scenario starts here' }).waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth), false);
  await page.screenshot({ path: 'Artifacts/empty-phone.png', fullPage: true });
  await page.getByRole('button', { name: 'Create trench test fixture' }).click();
  await page.getByRole('heading', { name: 'Active phase: induct' }).waitFor();
  for (const label of ['PPE station','Excavation edge','Service mark-out','Permit board']) await page.getByRole('button', { name: label, exact: true }).click();
  await page.getByRole('button', { name: 'Continue phase' }).click();
  await page.getByRole('status').filter({ hasText: 'Host release is required' }).waitFor();
  await page.getByLabel('Simulate host release').check();
  await page.getByRole('button', { name: 'Continue phase' }).click();
  await page.getByRole('heading', { name: 'Active phase: prove' }).waitFor();
  await page.getByRole('button', { name: 'Permit board', exact: true }).click();
  await page.getByRole('button', { name: 'Continue phase' }).click();
  await page.getByRole('button', { name: 'Test complete' }).waitFor();
  const log = await page.getByLabel('Host event log').textContent();
  assert.ok(log.includes('evidence.requested') && log.includes('scenario.completed'));
  const packageDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export package + media' }).click();
  const backup = await packageDownload;
  const packageText = await readFile(await backup.path(), 'utf8');
  await backup.saveAs('Artifacts/trench-browser.milzet-package.json');
  const parsed = JSON.parse(packageText);
  assert.equal(parsed.files.length, 2);
  const image = parsed.files.find(f => f.path.endsWith('.png'));
  await page.getByLabel('Replace image plate', { exact: true }).setInputFiles({ name: 'onsite-test.png', mimeType: 'image/png', buffer: Buffer.from(image.base64, 'base64') });
  await page.getByRole('status').filter({ hasText: 'Package and all media saved' }).waitFor();
  const wav = parsed.files.find(f => f.path.endsWith('.wav'));
  await page.getByLabel('Import WAV narration', { exact: true }).setInputFiles({ name: 'test-cue.wav', mimeType: 'audio/wav', buffer: Buffer.from(wav.base64, 'base64') });
  await page.getByRole('status').filter({ hasText: 'Package and all media saved' }).waitFor();
  await page.reload();
  await page.getByRole('heading', { name: 'Active phase: induct' }).waitFor();
  const damaged = { ...parsed, manifestSha256: 'broken' };
  await page.getByLabel('Open playable package', { exact: true }).setInputFiles({ name: 'broken.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(damaged)) });
  await page.getByRole('status').filter({ hasText: 'Manifest checksum mismatch' }).waitFor();
  await page.getByLabel('Open playable package', { exact: true }).setInputFiles({ name: 'restored.json', mimeType: 'application/json', buffer: Buffer.from(packageText) });
  await page.getByRole('status').filter({ hasText: 'Package and all media saved' }).waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth), false);
  await page.screenshot({ path: 'Artifacts/package-phone.png', fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1100 });
  await page.screenshot({ path: 'Artifacts/package-desktop.png', fullPage: true });
  await page.getByLabel('Create scenario from image', {exact:true}).setInputFiles({ name:'authored-local.png',mimeType:'image/png',buffer:Buffer.from(image.base64,'base64') });
  await page.getByRole('status').filter({hasText:'Package and all media saved'}).waitFor();
  await page.getByLabel('Scenario title', {exact:true}).fill('Authored trench workflow');
  await page.getByLabel('Hotspot label', {exact:true}).fill('PPE check');
  await page.getByLabel('Prompt or overlay text').fill('Author supplied PPE prompt');
  await page.getByLabel('Horizontal position').fill('0.15');
  await page.getByLabel('Vertical position').fill('0.25');
  for (const label of ['Edge check','Mark-out check','Permit check']) {
    await page.getByRole('button',{name:'Add hotspot',exact:true}).click();
    await page.getByLabel('Hotspot label',{exact:true}).fill(label);
    await page.getByLabel('Horizontal position').fill(label==='Edge check'?'0.42':label==='Mark-out check'?'0.64':'0.85');
    await page.getByLabel('Vertical position').fill(label==='Edge check'?'0.55':label==='Mark-out check'?'0.4':'0.22');
  }
  const plate = page.locator('.composition-plate');
  const bounds = await plate.boundingBox();
  await plate.click({position:{x:bounds.width*.75,y:bounds.height*.8}});
  await page.getByLabel('Request evidence from host').check();
  await page.getByLabel('Enable shadow').check();
  await page.getByLabel('Enable perform').check();
  await page.getByLabel('Enable prove').check();
  await page.getByLabel('Host release after induct').check();
  await page.getByLabel('Horizontal position').fill('2');
  await page.getByRole('button',{name:'Apply composition',exact:true}).click();
  await page.getByRole('status').filter({hasText:'Invalid hotspot anchor'}).waitFor();
  await page.getByLabel('Horizontal position').fill('0.75');
  await page.getByRole('button',{name:'Apply composition',exact:true}).click();
  await page.getByRole('status').filter({hasText:'Package and all media saved'}).waitFor();
  await page.getByLabel('Import WAV narration',{exact:true}).setInputFiles({name:'narration.wav',mimeType:'audio/wav',buffer:Buffer.from(wav.base64,'base64')});
  await page.getByRole('status').filter({hasText:'Package and all media saved'}).waitFor();
  await page.getByRole('button',{name:'Edit hotspot 4',exact:true}).click();
  const audioId=await page.getByLabel('Narration asset',{exact:true}).locator('option').nth(1).getAttribute('value');
  await page.getByLabel('Narration asset',{exact:true}).selectOption(audioId);
  await page.getByRole('button',{name:'Apply composition',exact:true}).click();
  await page.getByRole('status').filter({hasText:'Package and all media saved'}).waitFor();
  const authoredEvent=page.waitForEvent('download');
  await page.getByRole('button',{name:'Export package + media'}).click();
  const authoredDownload=await authoredEvent;
  await authoredDownload.saveAs('Artifacts/authored-browser.milzet-package.json');
  const authored=JSON.parse(await readFile(await authoredDownload.path(),'utf8'));
  const composition=JSON.parse(authored.manifest);
  assert.equal(composition.fixture,false);
  assert.equal(composition.title,'Authored trench workflow');
  assert.equal(composition.hotspots.length,4);
  assert.equal(composition.phases.length,4);
  assert.equal(composition.hotspots[3].x,.75);
  assert.ok(Math.abs(composition.hotspots[3].y-.8)<.01);
  assert.equal(composition.hotspots[3].narrationAssetId,audioId);
  assert.equal(composition.phases[0].gate,'host');
  await page.reload();
  await page.getByLabel('Scenario title',{exact:true}).waitFor();
  assert.equal(await page.getByLabel('Scenario title',{exact:true}).inputValue(),'Authored trench workflow');
  for(const label of ['PPE check','Edge check','Mark-out check','Permit check']) await page.getByRole('button',{name:label,exact:true}).click();
  await page.getByRole('button',{name:'Continue phase'}).click();
  await page.getByRole('status').filter({hasText:'Host release is required'}).waitFor();
  await page.getByLabel('Simulate host release').check();
  await page.getByRole('button',{name:'Continue phase'}).click();
  await page.getByRole('heading',{name:'Active phase: shadow'}).waitFor();
  await page.screenshot({path:'Artifacts/composer-desktop.png',fullPage:true});
  await page.setViewportSize({width:375,height:812});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth),false);
  await page.screenshot({path:'Artifacts/composer-phone.png',fullPage:true});
  await page.getByText('Source library, revisions and generation requests',{exact:true}).click();
  await page.getByLabel('Content owner',{exact:true}).fill('Test client');
  await page.getByLabel('Usage rights or licence',{exact:true}).fill('Client-owned test source');
  await page.getByLabel('Import original source',{exact:true}).setInputFiles({name:'source.png',mimeType:'image/png',buffer:Buffer.from(image.base64,'base64')});
  await page.getByRole('status').filter({hasText:'Source library saved locally'}).waitFor();
  await page.getByRole('button',{name:'Archive current scenario revision',exact:true}).click();
  await page.getByRole('status').filter({hasText:'Source library saved locally'}).waitFor();
  await page.getByLabel('Generation provider',{exact:true}).selectOption('meshy');
  await page.getByLabel('Generation prompt',{exact:true}).fill('A plain inspection marker for a procedural test');
  await page.getByRole('button',{name:'Prepare generation request',exact:true}).click();
  await page.getByRole('status').filter({hasText:'Source library saved locally'}).waitFor();
  const sourcesEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Back up source library',exact:true}).click();const sourcesDownload=await sourcesEvent;
  const sourceBackup=JSON.parse(await readFile(await sourcesDownload.path(),'utf8'));
  assert.equal(sourceBackup.assets.length,1);assert.equal(sourceBackup.revisions.length,1);assert.equal(sourceBackup.jobs[0].status,'prepared');assert.equal(sourceBackup.assets[0].provenance.owner,'Test client');
  await page.reload();await page.getByText('Source library, revisions and generation requests',{exact:true}).click();await page.getByRole('button',{name:'Download original',exact:true}).waitFor();
  const corruptedSource=structuredClone(sourceBackup);corruptedSource.assets[0].sha256='bad';
  await page.getByLabel('Restore source backup',{exact:true}).setInputFiles({name:'invalid-sources.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(corruptedSource))});
  await page.getByRole('status').filter({hasText:'Source checksum mismatch'}).waitFor();await page.getByRole('button',{name:'Download original',exact:true}).waitFor();
  await page.getByRole('button',{name:'Create scenario from this source',exact:true}).click();
  await page.getByRole('status').filter({hasText:'Package and all media saved'}).waitFor();
  assert.equal(await page.getByLabel('Scenario title',{exact:true}).inputValue(),'source.png');
  for(const projection of ['equirect180','equirect360']) {
    const panorama=await page.evaluate(kind=>{const c=document.createElement('canvas');c.width=kind==='equirect180'?512:1024;c.height=512;const x=c.getContext('2d');x.fillStyle='#cc3333';x.fillRect(0,0,c.width,c.height);for(const [a,b,color] of [[.125,.375,'#cccc33'],[.375,.625,'#3366cc'],[.625,.875,'#33cc66']]){x.fillStyle=color;x.fillRect(c.width*a,0,c.width*(b-a),c.height);}return c.toDataURL('image/png').split(',')[1];},projection);
    await page.getByLabel('Create scenario from image',{exact:true}).setInputFiles({name:projection+'.png',mimeType:'image/png',buffer:Buffer.from(panorama,'base64')});
    await page.getByRole('status').filter({hasText:'Package and all media saved'}).waitFor();
    await page.getByLabel('Source projection',{exact:true}).selectOption(projection);
    await page.getByLabel('Vertical position').fill('0.65');
    await page.getByRole('button',{name:'Apply composition',exact:true}).click();
    await page.getByRole('status').filter({hasText:'Package and all media saved'}).waitFor();
    const exported=page.waitForEvent('download');await page.getByRole('button',{name:'Export package + media'}).click();const file=await exported;
    await file.saveAs('Artifacts/'+projection+'-browser.milzet-package.json');
    const envelope=JSON.parse(await readFile(await file.path(),'utf8'));assert.equal(envelope.formatVersion,2);
    assert.equal(JSON.parse(envelope.manifest).plate.projection,projection);
    await page.setViewportSize({width:1440,height:1000});
    await page.locator('.scene-view').screenshot({path:'Artifacts/'+projection+'-front.png'});
    const rect=await page.locator('.scene-view canvas').boundingBox();await page.mouse.move(rect.x+rect.width*.8,rect.y+rect.height*.5);await page.mouse.down();await page.mouse.move(rect.x+rect.width*.2,rect.y+rect.height*.5,{steps:15});await page.mouse.up();
    await page.locator('.scene-view').screenshot({path:'Artifacts/'+projection+'-turned.png'});
    await page.reload();await page.getByLabel('Source projection',{exact:true}).waitFor();assert.equal(await page.getByLabel('Source projection',{exact:true}).inputValue(),projection);
  }
  execFileSync('/opt/homebrew/bin/ffmpeg',['-v','error','-y','-f','lavfi','-i','color=c=blue:s=640x320:r=24:d=3','-c:v','libx264','-pix_fmt','yuv420p','-movflags','+faststart','Artifacts/test-clip.mp4']);
  await page.getByLabel('Create scenario from video',{exact:true}).setInputFiles({name:'test-clip.mp4',mimeType:'video/mp4',buffer:await readFile('Artifacts/test-clip.mp4')});
  await page.getByRole('status').filter({hasText:'Package and all media saved'}).waitFor();
  await page.getByLabel('Source projection',{exact:true}).selectOption('equirect360');
  await page.getByRole('button',{name:'Apply composition',exact:true}).click();
  await page.getByRole('status').filter({hasText:'Package and all media saved'}).waitFor();
  await page.getByRole('button',{name:'Play / pause clip',exact:true}).click();
  await page.waitForFunction(()=>Number(document.querySelector('[aria-label="Clip time"]').value)>.3);
  await page.getByRole('button',{name:'Play / pause clip',exact:true}).click();
  await page.locator('.scene-view').screenshot({path:'Artifacts/video-browser.png'});
  const videoExport=page.waitForEvent('download');await page.getByRole('button',{name:'Export package + media'}).click();const videoFile=await videoExport;await videoFile.saveAs('Artifacts/video-browser.milzet-package.json');
  assert.equal(JSON.parse(await readFile(await videoFile.path(),'utf8')).formatVersion,3);
  await page.getByLabel('Open playable package',{exact:true}).setInputFiles({name:'model-base.json',mimeType:'application/json',buffer:Buffer.from(packageText)});
  await page.getByRole('status').filter({hasText:'Package and all media saved'}).waitFor();
  await page.getByLabel('Add GLB model',{exact:true}).setInputFiles({name:'test-triangle.glb',mimeType:'model/gltf-binary',buffer:Buffer.from(triangleGlb())});
  await page.getByRole('status').filter({hasText:'Package and all media saved'}).waitFor();
  await page.getByText('test-triangle.glb',{exact:true}).click();
  await page.getByLabel('test-triangle.glb position X',{exact:true}).fill('0.25');
  await page.getByLabel('Linked hotspot test-triangle.glb',{exact:true}).selectOption('point-1');
  await page.getByRole('button',{name:'Apply composition',exact:true}).click();
  await page.getByRole('status').filter({hasText:'Package and all media saved'}).waitFor();
  const modelExport=page.waitForEvent('download');await page.getByRole('button',{name:'Export package + media'}).click();const modelFile=await modelExport;await modelFile.saveAs('Artifacts/model-browser.milzet-package.json');
  const modelPackage=JSON.parse(await readFile(await modelFile.path(),'utf8'));assert.equal(modelPackage.formatVersion,4);assert.equal(JSON.parse(modelPackage.manifest).objects[0].position[0],.25);
  await page.locator('.scene-view').screenshot({path:'Artifacts/model-browser.png'});
  assert.deepEqual(errors, []);
  console.log('PASS: startup, create, reload, export, safe invalid import, valid import, desktop and 375px layout; zero browser errors; playable media backup/recovery/import and host gate/events passed.');
} finally { await browser?.close(); await server.close(); }
