import { chromium } from 'playwright';
import { createServer } from 'vite';
import { mkdir, readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const server = await createServer({ server: { host: '127.0.0.1', port: 0 } });
let browser;
try {
  await server.listen();
  const address = server.httpServer.address();
  browser = await chromium.launch({ channel: 'chrome', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(`http://127.0.0.1:${address.port}`);
  await page.getByRole('heading', { name: 'Your first scenario starts here' }).waitFor();
  await mkdir('Artifacts', { recursive: true });
  await page.screenshot({ path: 'Artifacts/empty-desktop.png', fullPage: true });
  await page.getByLabel('Project title').fill('Client site induction');
  await page.getByLabel('Environment template').selectOption('Site');
  await page.getByRole('button', { name: 'Create empty project' }).click();
  await page.getByRole('heading', { name: 'Client site induction' }).waitFor();
  await page.reload();
  await page.getByRole('heading', { name: 'Client site induction' }).waitFor();
  const event = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export draft' }).click();
  const download = await event;
  const draft = JSON.parse(await readFile(await download.path(), 'utf8'));
  assert.equal(draft.title, 'Client site induction');
  assert.deepEqual(draft.assets, []);
  assert.deepEqual(draft.targets, ['webxr', 'unity']);
  await page.getByLabel('Open draft', { exact: true }).setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{"schemaVersion":99}') });
  await page.getByRole('status').filter({ hasText: 'Unexpected or missing' }).waitFor();
  await page.getByRole('heading', { name: 'Client site induction' }).waitFor();
  const imported = { ...draft, title: 'Imported draft' };
  await page.getByLabel('Open draft', { exact: true }).setInputFiles({ name: 'valid.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(imported)) });
  await page.getByRole('heading', { name: 'Imported draft' }).waitFor();
  await page.screenshot({ path: 'Artifacts/project-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 375, height: 812 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth), false);
  await page.screenshot({ path: 'Artifacts/project-phone.png', fullPage: true });
  await page.evaluate(() => localStorage.clear());
  await page.reload();
  await page.getByRole('heading', { name: 'Your first scenario starts here' }).waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth), false);
  await page.screenshot({ path: 'Artifacts/empty-phone.png', fullPage: true });
  await page.getByRole('button', { name: 'Create trench test fixture' }).click();
  await page.getByRole('heading', { name: 'Active phase: induct' }).waitFor();
  for (const label of ['PPE station','Excavation edge','Service mark-out','Permit board']) await page.getByRole('button', { name: label, exact: true }).click();
  await page.getByRole('button', { name: 'Continue phase' }).click();
  await page.getByRole('status').filter({ hasText: 'Host release is required' }).waitFor();
  await page.getByLabel('Simulate host release').check();
  await page.getByRole('button', { name: 'Continue phase' }).click();
  await page.getByRole('heading', { name: 'Active phase: prove' }).waitFor();
  await page.getByRole('button', { name: 'Permit board', exact: true }).click();
  await page.getByRole('button', { name: 'Continue phase' }).click();
  await page.getByRole('button', { name: 'Test complete' }).waitFor();
  const log = await page.getByLabel('Host event log').textContent();
  assert.ok(log.includes('evidence.requested') && log.includes('scenario.completed'));
  const packageDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export package + media' }).click();
  const backup = await packageDownload;
  const packageText = await readFile(await backup.path(), 'utf8');
  await backup.saveAs('Artifacts/trench-browser.milzet-package.json');
  const parsed = JSON.parse(packageText);
  assert.equal(parsed.files.length, 2);
  const image = parsed.files.find(f => f.path.endsWith('.png'));
  await page.getByLabel('Replace image plate', { exact: true }).setInputFiles({ name: 'onsite-test.png', mimeType: 'image/png', buffer: Buffer.from(image.base64, 'base64') });
  await page.getByRole('status').filter({ hasText: 'Package and all media saved' }).waitFor();
  const wav = parsed.files.find(f => f.path.endsWith('.wav'));
  await page.getByLabel('Import WAV narration', { exact: true }).setInputFiles({ name: 'test-cue.wav', mimeType: 'audio/wav', buffer: Buffer.from(wav.base64, 'base64') });
  await page.getByRole('status').filter({ hasText: 'Package and all media saved' }).waitFor();
  await page.reload();
  await page.getByRole('heading', { name: 'Active phase: induct' }).waitFor();
  const damaged = { ...parsed, manifestSha256: 'broken' };
  await page.getByLabel('Open playable package', { exact: true }).setInputFiles({ name: 'broken.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(damaged)) });
  await page.getByRole('status').filter({ hasText: 'Manifest checksum mismatch' }).waitFor();
  await page.getByLabel('Open playable package', { exact: true }).setInputFiles({ name: 'restored.json', mimeType: 'application/json', buffer: Buffer.from(packageText) });
  await page.getByRole('status').filter({ hasText: 'Package and all media saved' }).waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth), false);
  await page.screenshot({ path: 'Artifacts/package-phone.png', fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1100 });
  await page.screenshot({ path: 'Artifacts/package-desktop.png', fullPage: true });
  assert.deepEqual(errors, []);
  console.log('PASS: startup, create, reload, export, safe invalid import, valid import, desktop and 375px layout; zero browser errors; playable media backup/recovery/import and host gate/events passed.');
} finally { await browser?.close(); await server.close(); }
