import { chromium } from 'playwright';
import { createServer } from 'vite';
import { mkdir, readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const server = await createServer({ server: { host: '127.0.0.1', port: 0 } });
let browser;
try {
  await server.listen();
  const address = server.httpServer.address();
  browser = await chromium.launch({ channel: 'chrome', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(`http://127.0.0.1:${address.port}`);
  await page.getByRole('heading', { name: 'Your first scenario starts here' }).waitFor();
  await mkdir('Artifacts', { recursive: true });
  await page.screenshot({ path: 'Artifacts/empty-desktop.png', fullPage: true });
  await page.getByLabel('Project title').fill('Client site induction');
  await page.getByLabel('Environment template').selectOption('Site');
  await page.getByRole('button', { name: 'Create empty project' }).click();
  await page.getByRole('heading', { name: 'Client site induction' }).waitFor();
  await page.reload();
  await page.getByRole('heading', { name: 'Client site induction' }).waitFor();
  const event = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export draft' }).click();
  const download = await event;
  const draft = JSON.parse(await readFile(await download.path(), 'utf8'));
  assert.equal(draft.title, 'Client site induction');
  assert.deepEqual(draft.assets, []);
  assert.deepEqual(draft.targets, ['webxr', 'unity']);
  await page.getByLabel('Open draft', { exact: true }).setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{"schemaVersion":99}') });
  await page.getByRole('status').filter({ hasText: 'Unexpected or missing' }).waitFor();
  await page.getByRole('heading', { name: 'Client site induction' }).waitFor();
  const imported = { ...draft, title: 'Imported draft' };
  await page.getByLabel('Open draft', { exact: true }).setInputFiles({ name: 'valid.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(imported)) });
  await page.getByRole('heading', { name: 'Imported draft' }).waitFor();
  await page.screenshot({ path: 'Artifacts/project-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 375, height: 812 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth), false);
  await page.screenshot({ path: 'Artifacts/project-phone.png', fullPage: true });
  await page.evaluate(() => localStorage.clear());
  await page.reload();
  await page.getByRole('heading', { name: 'Your first scenario starts here' }).waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth), false);
  await page.screenshot({ path: 'Artifacts/empty-phone.png', fullPage: true });
  assert.deepEqual(errors, []);
  console.log('PASS: startup, create, reload, export, safe invalid import, valid import, desktop and 375px layout; zero browser errors.');
} finally { await browser?.close(); await server.close(); }
