import test from 'node:test';
import assert from 'node:assert/strict';
import {checkPilotStructure} from '../Shared/pilot-checks.mjs';
import {pilotTypes,emptyContext} from '../Shared/context.mjs';
import {validateManifest} from '../Shared/package.mjs';
const scene=(id,projection='flat',mime='image/png')=>validateManifest({id,title:'Client structural test',fixture:true,entryPhase:'induct',context:{...emptyContext(),sourceCitation:'Client reference',externalStreamRef:'External session reference'},plate:{assetId:'plate',projection},assets:[{id:'plate',path:'assets/plate.'+(mime==='video/mp4'?'mp4':'png'),mime,bytes:1,sha256:'0'.repeat(64)},{id:'voice',path:'assets/voice.wav',mime:'audio/wav',bytes:1,sha256:'0'.repeat(64)}],hotspots:Array.from({length:4},(_,i)=>({id:'point-'+i,label:'Client point',text:'Client prompt',x:.5,y:.5,narrationAssetId:'',evidence:false})),phases:['induct','shadow','perform','prove'].map((id,i,list)=>({id,hotspotIds:['point-0','point-1','point-2','point-3'],next:list[i+1]||'',gate:'none'})),activities:[{kind:'acknowledgement',phase:'induct'},{kind:'observation',phase:'prove'},{kind:'field',phase:'perform'},...Array.from({length:3},()=>({kind:'quiz',phase:'prove'}))].map((a,i)=>({...a,id:'task-'+i,prompt:'Client authored prompt',choices:a.kind==='quiz'?['Client option A','Client option B']:[],hint:'',maxHints:0,startTime:0,endTime:0,citation:''})),presentation:{overlays:[],demonstration:{phase:'shadow',duration:90,narrationAssetId:'voice',path:[],cues:[]}}});
test('five pilot structure checks evaluate valid manifests and distinguish scaffolding from client acceptance',()=>{
 const scenes=[...Array.from({length:6},(_,i)=>scene('still-'+i)),scene('capture','equirect180','video/mp4')];for(const type of pilotTypes.filter(Boolean)){const report=checkPilotStructure(type,scenes);assert.equal(report.complete,true,type);assert.match(report.acceptance,/Structure only/);const incomplete=scene('blank');incomplete.context=emptyContext();assert.equal(checkPilotStructure(type,[validateManifest(incomplete)]).complete,false,type);}
 assert.equal(checkPilotStructure('First-aid switch test',[...Array(6).fill(scene('same')),scene('capture','equirect180')]).complete,false);
 const sphere=checkPilotStructure('Trench and fibre duct',[scene('sphere','equirect360')]);assert.equal(sphere.requirements.find(r=>r.label==='180° or 360° source').passed,true);assert.equal(checkPilotStructure('First-aid switch test',[...Array.from({length:6},(_,i)=>scene('still-'+i)),scene('sphere','equirect360')]).complete,true);assert.equal(checkPilotStructure('Trench and fibre duct',[scene('flat-only')]).requirements.find(r=>r.label==='180° or 360° source').passed,false);
});
