using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;
namespace Milzet.Content {
[Serializable] public class HostEvent {
 public string activityId="";public string response="";public string eventId;public string packageId;public string revision;public string phase;public string type;public string hotspotId;
}
public sealed partial class PackagePlayer : MonoBehaviour {
 public LoadedPackage Loaded {get;private set;}
 public PackageSession Session {get;private set;}
 public Camera ViewCamera {get;private set;}
 public AudioSource Narration {get;private set;}
 public Texture2D PlateTexture {get;private set;}
 public readonly List<HostEvent> Events=new List<HostEvent>();
 public readonly Dictionary<string,GameObject> Markers=new Dictionary<string,GameObject>();
 public readonly Dictionary<string,AudioClip> Clips=new Dictionary<string,AudioClip>();
 public bool SimulatedHostRelease;
 public Func<string,string,bool> Authorize;
 public event Action<HostEvent> HostEventEmitted;
 public string SelectedId {get;private set;}="";
 public string Message {get;private set;}="Open a portable Milzet package to begin.";
 readonly List<UnityEngine.Object> owned=new List<UnityEngine.Object>();
 GameObject content;string sessionId;int sequence;string packagePath="";Vector2 scroll;float yaw,pitch;string activityResponse="";readonly HashSet<string> pausedCues=new HashSet<string>();
 public void OpenFile(string path) {var info=new FileInfo(path);PackageReader.Require(info.Length<=120000000,"Document exceeds 120 MB.");Open(File.ReadAllText(path));packagePath=path;}
 internal void OpenScene(string text) {
  PackageReader.Require(!ModelsLoading,"Model import already in progress.");PackageReader.Require(!VideoLoading || preparedVideo!=null,"Video import already in progress.");
  var next=PackageReader.Open(text);if(next.Manifest.objects!=null && next.Manifest.objects.Length>0 && preparedModels==null){BeginModels(text,next);return;}if(next.Manifest.assets.First(a=>a.id==next.Manifest.plate.assetId).mime=="video/mp4" && preparedVideo==null){BeginVideo(text,next);return;}var texture=new Texture2D(2,2,TextureFormat.RGBA32,false);var clips=new Dictionary<string,AudioClip>();var overlayTextures=new Dictionary<string,Texture2D>();
  try {if(preparedVideo==null)PackageReader.Require(ImageConversion.LoadImage(texture,next.Assets[next.Manifest.plate.assetId]),"Unable to decode image plate.");if(next.Manifest.presentation!=null){if(next.Manifest.presentation.overlays.Length>0)PackageReader.Require(TMPro.TMP_Settings.defaultFontAsset!=null,"TMP font resources missing.");foreach(var id in next.Manifest.presentation.overlays.Where(o=>o.imageAssetId!="").Select(o=>o.imageAssetId).Distinct()){var image=new Texture2D(2,2,TextureFormat.RGBA32,false);overlayTextures.Add(id,image);PackageReader.Require(ImageConversion.LoadImage(image,next.Assets[id]),"Overlay image decode failed.");}}foreach(var asset in next.Manifest.assets.Where(a=>a.mime=="audio/wav"))clips.Add(asset.id,WaveDecoder.Decode(next.Assets[asset.id],asset.id));}
  catch{DestroyImmediate(texture);foreach(var image in overlayTextures.Values)DestroyImmediate(image);foreach(var clip in clips.Values)DestroyImmediate(clip);throw;}
  Clear();Loaded=next;PlateTexture=texture;owned.Add(texture);foreach(var image in overlayTextures){OverlayTextures.Add(image.Key,image.Value);owned.Add(image.Value);}foreach(var clip in clips){Clips.Add(clip.Key,clip.Value);owned.Add(clip.Value);}Events.Clear();pausedCues.Clear();sequence=0;sessionId=Guid.NewGuid().ToString("N");SimulatedHostRelease=false;SelectedId="";yaw=0;pitch=0;
  Session=new PackageSession(next,(type,phase,id)=>Record(type,phase,id));Session.ActivityEvent=(type,id,response)=>Record(type,Session.PhaseId,"",id,response);
  content=new GameObject("Milzet generated preview");content.transform.SetParent(transform,false);
  if(TrackedOrigin==null){ViewCamera=new GameObject("Package camera").AddComponent<Camera>();ViewCamera.transform.SetParent(content.transform,false);ViewCamera.transform.position=new Vector3(0,1.5f,next.Manifest.plate.projection=="flat"?-1:0);ViewCamera.transform.rotation=Quaternion.identity;ViewCamera.fieldOfView=60;ViewCamera.nearClipPlane=.1f;ViewCamera.farClipPlane=100;ViewCamera.clearFlags=CameraClearFlags.SolidColor;ViewCamera.backgroundColor=new Color(21/255f,42/255f,39/255f);ViewCamera.gameObject.AddComponent<AudioListener>();}
  Narration=content.AddComponent<AudioSource>();Narration.playOnAwake=false;Narration.spatialBlend=0;Narration.volume=.25f;
  Mesh mesh=RoundedPlate();if(next.Manifest.plate.projection!="flat"){DestroyImmediate(mesh);mesh=ProjectionMesh.Create(next.Manifest.plate.projection);}owned.Add(mesh);
  var plate=new GameObject("Image plate");plate.transform.SetParent(content.transform,false);plate.transform.position=next.Manifest.plate.projection=="flat"?new Vector3(0,1.5f,2):Vector3.zero;plate.AddComponent<MeshFilter>().sharedMesh=mesh;var shader=Shader.Find("Unlit/Texture");PackageReader.Require(shader!=null,"Unlit/Texture shader missing.");var material=new Material(shader){mainTexture=preparedVideo!=null?(Texture)preparedVideo.targetTexture:texture};owned.Add(material);plate.AddComponent<MeshRenderer>().sharedMaterial=material;flatDisplay=null;if(next.Manifest.plate.projection=="flat"){flatDisplay=new GameObject("Movable lesson display").transform;flatDisplay.SetParent(content.transform,false);flatDisplay.position=plate.transform.position;plate.transform.SetParent(flatDisplay,true);float aspect=(float)material.mainTexture.width/material.mainTexture.height;plate.transform.localScale=aspect>4f/2.4f?new Vector3(1,(4/aspect)/2.4f,1):new Vector3(2.4f*aspect/4,1,1);}
  foreach(var h in next.Manifest.hotspots) {var marker=GameObject.CreatePrimitive(PrimitiveType.Sphere);marker.name=h.id;marker.transform.SetParent(content.transform,false);marker.transform.position=Anchor(h,next.Manifest.plate.projection);if(flatDisplay!=null){var point=marker.transform.position-flatDisplay.position;point.x*=plate.transform.localScale.x;point.y*=plate.transform.localScale.y;marker.transform.position=flatDisplay.position+point;}marker.transform.localScale=Vector3.one*.13f;var colorShader=Shader.Find("Unlit/Color");PackageReader.Require(colorShader!=null,"Unlit/Color shader missing.");var mat=new Material(colorShader){color=new Color(214/255f,248/255f,149/255f)};owned.Add(mat);marker.GetComponent<Renderer>().sharedMaterial=mat;Markers.Add(h.id,marker);if(flatDisplay!=null)marker.transform.SetParent(flatDisplay,true);}
  if(preparedVideo!=null){Video=preparedVideo;Video.transform.SetParent(content.transform,false);owned.Add(Video.targetTexture);preparedVideo=null;}AdoptModels();BuildPresentation();BuildDisplayHandle();PlaceInitialDisplay();ApplyRoomPlacement();WorldTab("media");Physics.SyncTransforms();Message="Choose Inspect to select a marker, or Playback to play media.";if(TrackedOrigin!=null){ShowWorldControls(true);}Debug.Log("MILZET_PACKAGE_READY "+next.Manifest.id+" rig="+(TrackedOrigin!=null));
 }
 void Record(string type,string phase,string hotspotId="",string activityId="",string response=""){var e=new HostEvent{eventId=sessionId+":"+(++sequence),packageId=Loaded.Manifest.id,revision=Loaded.Revision,phase=phase,type=type,hotspotId=hotspotId,activityId=activityId,response=response};Events.Add(e);HostEventEmitted?.Invoke(e);}
 public static Vector3 Anchor(Hotspot h,string projection="flat") {var p=Projection.Anchor(h.x,h.y,projection);return new Vector3((float)p[0],(float)p[1],(float)p[2]);}
 public bool SelectRay(Ray ray) {if(SelectReferenceControls(ray))return true;if(SelectWorldControls(ray))return true;if(Physics.Raycast(ray,out var hit,100)){var marker=Markers.FirstOrDefault(p=>p.Value==hit.collider.gameObject);if(marker.Value!=null){Select(marker.Key);return true;}if(modelTargets.TryGetValue(hit.collider.gameObject,out var id)){Select(id);return true;}}return false;}
 public void SetView(float heading,float elevation){yaw=heading;pitch=Mathf.Clamp(elevation,-89,89);ViewCamera.transform.rotation=Quaternion.Euler(-pitch,yaw,0);}
 public void Select(string id) {Session.Select(id);SelectedId=id;Message=Loaded.Manifest.hotspots.First(h=>h.id==id).text;}
 public void Advance() {Session.Advance((from,to)=>Authorize!=null?Authorize(from,to):SimulatedHostRelease);SelectedId="";Message=Session.Complete?"Test scenario completed; local host event recorded.":"Phase advanced.";}
 public void PlaySelectedAudio() {PackageReader.Require(Loaded!=null && SelectedId!="","Select a hotspot first.");string id=Loaded.Manifest.hotspots.First(h=>h.id==SelectedId).narrationAssetId;PackageReader.Require(Clips.ContainsKey(id),"No supported narration clip.");Narration.clip=Clips[id];Narration.Play();}
 void Try(Action action){try{action();}catch(Exception e){Message=e.Message;}}
 public bool DemonstrationActive {get{return DemoPlayback!=null && Session?.PhaseId==Loaded?.Manifest.presentation?.demonstration?.phase;}}
 public double PlaybackTime {get{return DemonstrationActive?DemoPlayback.Time:Video!=null?Video.time:0;}}
 void Update(){UpdateTrackedRig();UpdatePresentation();UpdateWorldControls();if(Loaded==null || Session==null)return;var cue=(Loaded.Manifest.activities??new Activity[0]).FirstOrDefault(a=>a.phase==Session.PhaseId && !Session.CompletedActivities.Contains(a.id));if(cue!=null && cue.startTime>0 && PlaybackTime>=cue.startTime && pausedCues.Add(cue.id))PauseDemonstration();}
 void OnGUI() {
  if(TrackedOrigin!=null)return;
  if(SetupVisible || (SetupRequired && !SetupConfirmed)){if(SetupVisible && Event.current.type==EventType.MouseDown){var point=Event.current.mousePosition;Try(()=>SelectRay(ViewCamera.ScreenPointToRay(new Vector3(point.x,Screen.height-point.y,0))));}return;}
  float width=Mathf.Min(350,Screen.width-24);if(Loaded!=null && Event.current.type==EventType.MouseDown && Event.current.mousePosition.x>width+24){Vector2 p=Event.current.mousePosition;Try(()=>SelectRay(ViewCamera.ScreenPointToRay(new Vector3(p.x,Screen.height-p.y,0))));}
 GUILayout.BeginArea(new Rect(12,12,width,Screen.height-24),GUI.skin.box);scroll=GUILayout.BeginScrollView(scroll);GUILayout.Label("MILZET / NATIVE PACKAGE PREVIEW");packagePath=GUILayout.TextField(packagePath);if(GUILayout.Button("Open local package"))Try(()=>OpenFile(packagePath));
  if(Experience!=null){GUILayout.Label(Experience.Manifest.title+" / "+Journey.SceneId);SimulatedSceneRelease=GUILayout.Toggle(SimulatedSceneRelease,"Simulate scene release (test host)");GUI.enabled=!ExperienceLoading && !Journey.Complete;if(GUILayout.Button("Continue experience"))Try(AdvanceExperience);GUI.enabled=true;GUILayout.Label("Experience events: "+ExperienceEvents.Count);}
  if(Loaded!=null){if(GUILayout.Button(WorldControls!=null && WorldControls.gameObject.activeSelf?"Hide world controls":"Preview world controls"))ShowWorldControls(WorldControls==null || !WorldControls.gameObject.activeSelf);GUILayout.Label(Loaded.Manifest.title);if(Loaded.Manifest.context!=null){GUILayout.Label(Loaded.Manifest.context.occupationRef);GUILayout.Label(Loaded.Manifest.context.moduleRefs);GUILayout.Label(Loaded.Manifest.context.sourceCitation);}PresentationGUI();if(Video!=null && !DemonstrationActive){if(GUILayout.Button(Video.isPlaying?"Pause clip":"Play clip")){if(Video.isPlaying)Video.Pause();else Video.Play();}float seek=GUILayout.HorizontalSlider((float)Video.time,0,(float)Video.length);if(Mathf.Abs(seek-(float)Video.time)>.1f)Video.time=seek;}if(Loaded.Manifest.plate.projection!="flat"){GUILayout.Label("Look direction");float heading=GUILayout.HorizontalSlider(yaw,-180,180);float elevation=GUILayout.HorizontalSlider(pitch,-89,89);SetView(heading,elevation);}if(Loaded.Manifest.fixture)GUILayout.Label("TEST FIXTURE — NOT CLIENT INSTRUCTION");GUILayout.Label("Phase: "+Session.PhaseId);foreach(var id in Loaded.Manifest.phases.First(p=>p.id==Session.PhaseId).hotspotIds){if(GUILayout.Button(Loaded.Manifest.hotspots.First(h=>h.id==id).label))Try(()=>Select(id));}var activity=(Loaded.Manifest.activities??new Activity[0]).FirstOrDefault(a=>a.phase==Session.PhaseId && !Session.CompletedActivities.Contains(a.id));if(activity!=null){GUILayout.Label(activity.prompt);GUILayout.Label(activity.citation);if(activity.kind=="quiz"){foreach(var choice in activity.choices)if(GUILayout.Button(choice))Try(()=>Session.Respond(activity.id,choice,PlaybackTime));}else{if(activity.kind!="acknowledgement" && activity.kind!="step")activityResponse=GUILayout.TextField(activityResponse);if(GUILayout.Button("Submit activity response"))Try(()=>{Session.Respond(activity.id,activity.kind=="acknowledgement" || activity.kind=="step"?"acknowledged":activityResponse,PlaybackTime);activityResponse="";});}if(activity.hint!="" && activity.phase!="prove" && GUILayout.Button("Show activity hint"))Try(()=>Message=Session.Hint(activity.id));}SimulatedHostRelease=GUILayout.Toggle(SimulatedHostRelease,"Simulate host release (test host)");GUI.enabled=!Session.Complete;if(GUILayout.Button("Continue phase"))Try(Advance);GUI.enabled=true;if(GUILayout.Button("Play package audio"))Try(PlaySelectedAudio);GUILayout.Label("Host events: "+Events.Count);}
  GUILayout.Label(Message);GUILayout.EndScrollView();GUILayout.EndArea();
 }
 public void Clear() {ClearWorldControls();ClearPresentation();ClearModels();if(Video!=null)Video.Stop();Video=null;if(Narration!=null)Narration.Stop();if(content!=null)DestroyImmediate(content);foreach(var item in owned)if(item!=null)DestroyImmediate(item);owned.Clear();Markers.Clear();Clips.Clear();Loaded=null;Session=null;}
 void OnDestroy(){roomGeneration++;DiscardPreparedModels();Clear();ClearTrackedRig();}
}
}
