using System;
using System.Collections;
using System.IO;
using System.Linq;
using UnityEngine;
using TMPro;
namespace Milzet.Content {
public sealed class StandaloneVerification : MonoBehaviour {
 public void Begin(PackagePlayer player,string directory){StartCoroutine(Guard(Check(player,directory)));}
 IEnumerator Guard(IEnumerator task){while(true){bool more;try{more=task.MoveNext();}catch(Exception e){Debug.LogException(e);Application.Quit(1);yield break;}if(!more)yield break;yield return task.Current;}}
 static Texture2D Frame(Camera camera){var target=new RenderTexture(1200,720,24);target.Create();var previous=RenderTexture.active;var priorTarget=camera.targetTexture;float aspect=camera.aspect;try{camera.targetTexture=target;camera.aspect=1200f/720;Canvas.ForceUpdateCanvases();camera.Render();RenderTexture.active=target;var image=new Texture2D(1200,720,TextureFormat.RGB24,false);image.ReadPixels(new Rect(0,0,1200,720),0,0);image.Apply();return image;}finally{camera.targetTexture=priorTarget;camera.aspect=aspect;RenderTexture.active=previous;target.Release();DestroyImmediate(target);}}
 public static void CaptureVisibleControls(PackagePlayer player,string path){
  player.ShowWorldControls(true);var shown=Frame(player.ViewCamera);Texture2D hidden=null;
  try{PackageReader.Require(player.WorldControls.GetComponentsInChildren<TMP_Text>().Any(t=>t.textInfo.meshInfo.Any(m=>m.vertexCount>0)),"World controls have no rendered text geometry.");player.WorldControls.gameObject.SetActive(false);hidden=Frame(player.ViewCamera);var a=shown.GetPixels32();var b=hidden.GetPixels32();int changed=0;for(int i=0;i<a.Length;i++)if(Math.Abs(a[i].r-b[i].r)+Math.Abs(a[i].g-b[i].g)+Math.Abs(a[i].b-b[i].b)>20)changed++;PackageReader.Require(changed>3000,"World controls are occluded or outside the camera: "+changed+" visible pixels.");File.WriteAllBytes(path,shown.EncodeToPNG());}
  finally{player.WorldControls.gameObject.SetActive(true);DestroyImmediate(shown);if(hidden!=null)DestroyImmediate(hidden);}
 }
 IEnumerator Check(PackagePlayer player,string directory){
  float limit=Time.realtimeSinceStartup+60;while((player.ModelsLoading || player.VideoLoading || player.ExperienceLoading) && Time.realtimeSinceStartup<limit)yield return null;
  PackageReader.Require(player.Loaded!=null && player.Loaded.Manifest.id!="milzet-viewer-welcome","Standalone did not import requested package.");string revision=player.Loaded.Revision;player.ShowWorldControls(true);player.SeekDemonstration(1);yield return null;
  var overlay=player.OverlayObjects.Values.First();PackageReader.Require(overlay.activeSelf && player.DemoHighlight=="point-1" && player.WorldControls!=null,"Standalone presentation controls failed.");
  Directory.CreateDirectory(directory);CaptureVisibleControls(player,Path.Combine(directory,"standalone.png"));player.ToggleDemonstration();PackageReader.Require(player.DemoNarration.isPlaying,"Standalone narration engine failed.");player.PauseDemonstration();
  var args=Environment.GetCommandLineArgs();string fixtures=Path.GetDirectoryName(args[Array.IndexOf(args,"--milzet-package")+1]);
  player.OpenFile(Path.Combine(fixtures,"timed-presentation-browser.milzet-package.json"));player.ShowWorldControls(true);player.ToggleDemonstration();limit=Time.realtimeSinceStartup+8;while(player.DemoPlayback.Playing && Time.realtimeSinceStartup<limit)yield return null;PackageReader.Require(player.PlaybackTime>=.5 && player.PlaybackTime<1 && !player.DemoPlayback.Playing,"Still-image activity did not pause the demonstration.");player.ActivateWorldControl("activity");player.ActivateWorldControl("ack");PackageReader.Require(player.Session.CompletedActivities.Contains("timed-ack"),"Still-image timed response failed.");
  player.OpenFile(Path.Combine(fixtures,"phase-video-browser.milzet-package.json"));limit=Time.realtimeSinceStartup+60;while(player.VideoLoading && Time.realtimeSinceStartup<limit)yield return null;PackageReader.Require(player.Video!=null && !player.DemonstrationActive,"Video phase import failed: "+player.Message);player.ShowWorldControls(true);player.ActivateWorldControl("media");player.ActivateWorldControl("play");limit=Time.realtimeSinceStartup+8;while((player.Video.time<.5 || player.Video.isPlaying) && Time.realtimeSinceStartup<limit)yield return null;PackageReader.Require(player.PlaybackTime>=.5 && player.PlaybackTime<1 && !player.Video.isPlaying,"Video activity used the wrong phase clock.");player.ActivateWorldControl("tab-menu");player.ActivateWorldControl("activity");player.ActivateWorldControl("ack");PackageReader.Require(player.Session.CompletedActivities.Contains("timed-ack"),"Video timed response failed.");
  foreach(var id in player.Loaded.Manifest.phases.First(p=>p.id==player.Session.PhaseId).hotspotIds)player.Select(id);player.Advance();yield return null;PackageReader.Require(player.DemonstrationActive,"Demonstration phase did not become active.");player.ActivateWorldControl("tab-menu");player.ActivateWorldControl("media");player.ActivateWorldControl("play");limit=Time.realtimeSinceStartup+8;while(player.DemoPlayback.Time<.3 && Time.realtimeSinceStartup<limit)yield return null;PackageReader.Require(player.DemoPlayback.Time>=.3,"Video demonstration did not advance.");player.PauseDemonstration();var video=Frame(player.ViewCamera);try{PackageReader.Require(video.GetPixels().Count(pixel=>pixel.b>.7f && pixel.r<.15f)>100000,"Standalone video failed to render.");File.WriteAllBytes(Path.Combine(directory,"video.png"),video.EncodeToPNG());}finally{DestroyImmediate(video);}
  player.OpenFile(Path.Combine(fixtures,"model-browser.milzet-package.json"));limit=Time.realtimeSinceStartup+60;while(player.ModelsLoading && Time.realtimeSinceStartup<limit)yield return null;PackageReader.Require(player.ModelObjects.Count==1,"Standalone model failed to load: "+player.Message);var model=player.ModelObjects.Values.First();var ray=new Ray(player.ViewCamera.transform.position,(model.transform.position-player.ViewCamera.transform.position).normalized);PackageReader.Require(player.SelectRay(ray) && player.SelectedId=="point-1","Standalone model ray failed.");float previousAspect=player.ViewCamera.aspect;player.ViewCamera.aspect=1200f/720;var point=player.ViewCamera.WorldToViewportPoint(model.transform.position);var modelImage=Frame(player.ViewCamera);try{var pixel=modelImage.GetPixel((int)(point.x*1200),(int)(point.y*720));PackageReader.Require(pixel.r>.7f && pixel.b>.7f && pixel.g<.2f,"Standalone GLB shader failed: "+pixel);File.WriteAllBytes(Path.Combine(directory,"model.png"),modelImage.EncodeToPNG());}finally{player.ViewCamera.aspect=previousAspect;DestroyImmediate(modelImage);}
  player.OpenFile(Path.Combine(fixtures,"experience-browser.milzet-experience.json"));limit=Time.realtimeSinceStartup+60;while(player.ExperienceLoading && Time.realtimeSinceStartup<limit)yield return null;PackageReader.Require(player.Experience!=null && player.Experience.Manifest.scenes.Length==2,"Standalone experience import failed.");int sceneCount=0;
  while(!player.Journey.Complete){while(!player.Session.Complete){foreach(var id in player.Loaded.Manifest.phases.First(p=>p.id==player.Session.PhaseId).hotspotIds)player.Select(id);player.SimulatedHostRelease=true;player.Advance();}player.SimulatedSceneRelease=true;player.AdvanceExperience();limit=Time.realtimeSinceStartup+60;while(player.ExperienceLoading && Time.realtimeSinceStartup<limit)yield return null;PackageReader.Require(!player.ExperienceLoading,"Standalone scene transition timed out.");sceneCount++;PackageReader.Require(sceneCount<=2,"Standalone experience did not terminate.");}
  PackageReader.Require(sceneCount==2 && player.ExperienceEvents.Any(e=>e.type=="experience.completed"),"Standalone experience completion failed.");
  File.WriteAllText(Path.Combine(directory,"standalone-verification.json"),"{\"passed\":true,\"standalone\":true,\"platform\":\""+Application.platform+"\",\"revision\":\""+revision+"\",\"overlay\":true,\"renderedWorldControls\":true,\"narrationEngine\":true,\"timedStillActivity\":true,\"phaseVideoActivity\":true,\"videoRender\":true,\"glbRenderAndRay\":true,\"multiSceneCompletion\":true,\"headset\":\"not tested\"}");Application.Quit(0);
 }
}
}
