using System;
using System.Collections;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.LowLevel;
using UnityEngine.InputSystem.XR;
using UnityEngine.XR.OpenXR.Features.Interactions;
using TMPro;
using Milzet.Content;
namespace Milzet.Editor {
public static class XRVerification {
 public static void StartCheck(string directory,string output){var player=new GameObject("XR controls verification").AddComponent<PackagePlayer>();player.StartCoroutine(Guard(Check(player,directory,output)));}
 static IEnumerator Guard(IEnumerator task){while(true){bool more;try{more=task.MoveNext();}catch(Exception e){Debug.LogException(e);EditorApplication.Exit(1);yield break;}if(!more)yield break;yield return task.Current;}}
 static IEnumerator Check(PackagePlayer player,string directory,string output){
  player.OpenFile(Path.Combine(directory,"activities-browser.milzet-package.json"));float deadline=Time.realtimeSinceStartup+30;while(player.ModelsLoading && Time.realtimeSinceStartup<deadline)yield return null;
  player.ShowWorldControls(true);player.ActivateWorldControl("tab-menu");PackageReader.Require(player.WorldControls!=null && player.WorldButtons.ContainsKey("inspect"),"Native world controls missing.");var button=player.WorldButtons["inspect"];var ray=new Ray(player.ViewCamera.transform.position,(button.position-player.ViewCamera.transform.position).normalized);PackageReader.Require(player.SelectWorldControls(ray) && player.WorldButtons.Keys.Any(k=>k.StartsWith("select-")),"World control ray failed.");
  foreach(var id in player.Loaded.Manifest.phases.First(p=>p.id==player.Session.PhaseId).hotspotIds)player.ActivateWorldControl("select-"+id);player.ActivateWorldControl("tab-menu");player.ActivateWorldControl("activity");
  while(player.Loaded.Manifest.activities.Any(a=>a.phase==player.Session.PhaseId && !player.Session.CompletedActivities.Contains(a.id))){var a=player.Loaded.Manifest.activities.First(a=>a.phase==player.Session.PhaseId && !player.Session.CompletedActivities.Contains(a.id));if(a.kind=="quiz")player.ActivateWorldControl("choice-0");else if(a.kind=="acknowledgement" || a.kind=="step")player.ActivateWorldControl("ack");else{player.ActivateWorldControl("write");player.ActivateWorldControl("key-A");player.ActivateWorldControl("done");player.ActivateWorldControl("submit");}}
  PackageReader.Require(player.Events.Any(e=>e.type=="activity.responded"),"World activity response failed.");
  foreach(var text in player.WorldControls.GetComponentsInChildren<TMP_Text>())PackageReader.Require(text.font!=null && text.fontSize>=25 && text.transform.localScale==Vector3.one && text.transform.localPosition.z==0,"World text does not use physical UI sizing.");
  StandaloneVerification.CaptureVisibleControls(player,Path.Combine(output,"world-controls-native.png"));
  player.EnableTrackedRig();PackageReader.Require(player.TrackedOrigin!=null && player.ViewCamera.GetComponent<TrackedPoseDriver>()!=null,"Tracked rig missing.");var hmd=InputSystem.AddDevice<XRHMD>();using(StateEvent.From(hmd,out var inputEvent)){hmd.centerEyePosition.WriteValueIntoEvent(new Vector3(.2f,1.6f,.1f),inputEvent);hmd.centerEyeRotation.WriteValueIntoEvent(Quaternion.Euler(0,15,0),inputEvent);hmd.trackingState.WriteValueIntoEvent(63,inputEvent);hmd.isTracked.WriteValueIntoEvent(1f,inputEvent);InputSystem.QueueEvent(inputEvent);}InputSystem.Update();yield return null;PackageReader.Require(Vector3.Distance(player.ViewCamera.transform.localPosition,new Vector3(.2f,1.6f,.1f))<.001f,"Head pose input binding failed: camera="+player.ViewCamera.transform.localPosition+" input="+hmd.centerEyePosition.ReadValue()+" action="+player.ViewCamera.GetComponent<TrackedPoseDriver>().positionInput.action.ReadValue<Vector3>()+" tracking="+hmd.trackingState.ReadValue()+" enabled="+player.ViewCamera.GetComponent<TrackedPoseDriver>().positionInput.action.enabled);PackageReader.Require((bool)typeof(PackagePlayer).GetMethod("HeadTracked",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(player,null),"Head tracking rejected position/orientation with velocity flags.");InputSystem.RemoveDevice(hmd);
  player.ActivateWorldControl("tab-menu");var pointer=InputSystem.AddDevice<OculusTouchControllerProfile.OculusTouchController>();InputSystem.SetDeviceUsage(pointer,UnityEngine.InputSystem.CommonUsages.RightHand);yield return null;var aim=player.WorldButtons["inspect"].position;var start=new Vector3(0,1.2f,0);var space=player.TrackedOrigin.CameraFloorOffsetObject.transform;using(StateEvent.From(pointer,out var pointerEvent)){pointer.pointerPosition.WriteValueIntoEvent(space.InverseTransformPoint(start),pointerEvent);pointer.pointerRotation.WriteValueIntoEvent(Quaternion.Inverse(space.rotation)*Quaternion.LookRotation(aim-start),pointerEvent);pointer.isTracked.WriteValueIntoEvent(1f,pointerEvent);pointer.triggerPressed.WriteValueIntoEvent(1f,pointerEvent);InputSystem.QueueEvent(pointerEvent);}InputSystem.Update();yield return null;PackageReader.Require(player.WorldButtons.ContainsKey("inspect"),"Controller activated while held before neutral.");using(StateEvent.From(pointer,out var neutral)){pointer.triggerPressed.WriteValueIntoEvent(0f,neutral);InputSystem.QueueEvent(neutral);}InputSystem.Update();yield return null;using(StateEvent.From(pointer,out var press)){pointer.triggerPressed.WriteValueIntoEvent(1f,press);InputSystem.QueueEvent(press);}InputSystem.Update();yield return null;PackageReader.Require(player.WorldButtons.Keys.Any(k=>k.StartsWith("select-")),"Touch controller aim/select bindings failed. device="+pointer.layout+" tracked="+pointer.isTracked.ReadValue()+" trigger="+pointer.triggerPressed.ReadValue()+" position="+pointer.pointerPosition.ReadValue()+" rotation="+pointer.pointerRotation.ReadValue()+" actions="+String.Join(";",((System.Collections.Generic.List<InputAction>)typeof(PackagePlayer).GetField("xrActions",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).GetValue(player)).Where(a=>a.name.StartsWith("RightHand")).Select(a=>a.name+"="+a.ReadValueAsObject()+" pressed="+a.WasPressedThisFrame()))+" message="+player.Message);var origin=player.TrackedOrigin;var camera=player.ViewCamera;var originalActions=((System.Collections.Generic.List<InputAction>)typeof(PackagePlayer).GetField("xrActions",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).GetValue(player)).ToArray();
  using(StateEvent.From(pointer,out var releaseEvent)){pointer.triggerPressed.WriteValueIntoEvent(0f,releaseEvent);InputSystem.QueueEvent(releaseEvent);}InputSystem.Update();yield return null;
  var menu=player.WorldControls;var menuStart=menu.transform.position;var handle=menu.transform.TransformPoint(new Vector3(0,430,0));var grabRotation=Quaternion.LookRotation(handle-start);
  using(StateEvent.From(pointer,out var grabEvent)){pointer.pointerPosition.WriteValueIntoEvent(space.InverseTransformPoint(start),grabEvent);pointer.pointerRotation.WriteValueIntoEvent(Quaternion.Inverse(space.rotation)*grabRotation,grabEvent);pointer.gripPressed.WriteValueIntoEvent(1f,grabEvent);InputSystem.QueueEvent(grabEvent);}InputSystem.Update();yield return null;PackageReader.Require(player.MenuGrabbed,"Controller grip did not grab menu handle.");
  using(StateEvent.From(pointer,out var dragEvent)){pointer.pointerPosition.WriteValueIntoEvent(space.InverseTransformPoint(start+Vector3.left*.4f),dragEvent);InputSystem.QueueEvent(dragEvent);}InputSystem.Update();yield return null;PackageReader.Require(Vector3.Distance(menu.transform.position,menuStart+Vector3.left*.4f)<.01f,"Held controller did not translate menu.");
  using(StateEvent.From(pointer,out var releaseEvent)){pointer.gripPressed.WriteValueIntoEvent(0f,releaseEvent);InputSystem.QueueEvent(releaseEvent);}InputSystem.Update();yield return null;PackageReader.Require(!player.MenuGrabbed,"Controller release did not release menu.");var parked=menu.transform.position;var parkedRotation=menu.transform.rotation;
  player.ActivateWorldControl("tab-media");PackageReader.Require(Vector3.Distance(parked,menu.transform.position)<.001f,"Tab switch moved menu.");
  foreach(var file in new[]{"presentation-browser.milzet-package.json","equirect180-browser.milzet-package.json","equirect360-browser.milzet-package.json","phase-video-browser.milzet-package.json","experience-browser.milzet-experience.json"}){player.OpenFile(Path.Combine(directory,file));deadline=Time.realtimeSinceStartup+30;while((player.ModelsLoading || player.VideoLoading || player.ExperienceLoading) && Time.realtimeSinceStartup<deadline)yield return null;yield return null;PackageReader.Require(player.TrackedOrigin==origin && player.ViewCamera==camera && originalActions.All(a=>a.enabled),"Package transition rebuilt tracked rig or disabled actions: "+file);PackageReader.Require(player.WorldControls==menu && Vector3.Distance(parked,menu.transform.position)<.001f && Quaternion.Angle(parkedRotation,menu.transform.rotation)<.01f,"Package transition moved parked menu: "+file);player.ActivateWorldControl("tab-inspect");PackageReader.Require(player.WorldButtons.Keys.Any(k=>k.StartsWith("select-")),"Inspect unavailable after package transition.");}
  var before=origin.transform.position;player.MoveViewer(Vector2.up,.05f);PackageReader.Require(Vector3.Distance(before,origin.transform.position)>.01f,"Locomotion did not move origin.");var heading=origin.transform.rotation;player.TurnViewer(30);PackageReader.Require(Quaternion.Angle(heading,origin.transform.rotation)>29,"Snap turn failed.");player.ResetViewerPosition();
  InputSystem.RemoveDevice(pointer);
  var hand=InputSystem.AddDevice<HandInteractionProfile.HandInteraction>();InputSystem.SetDeviceUsage(hand,UnityEngine.InputSystem.CommonUsages.LeftHand);yield return null;
  handle=player.WorldButtons["tab-navigate"].position;var beforeHandButtons=String.Join(",",player.WorldButtons.Keys);start=handle-menu.transform.forward*.2f;menuStart=menu.transform.position;grabRotation=menu.transform.rotation;
  using(StateEvent.From(hand,out var handEvent)){hand.pointerPosition.WriteValueIntoEvent(space.InverseTransformPoint(start),handEvent);hand.pointerRotation.WriteValueIntoEvent(Quaternion.Inverse(space.rotation)*grabRotation,handEvent);hand.pointer.isTracked.WriteValueIntoEvent(1f,handEvent);hand.pinchPosition.WriteValueIntoEvent(space.InverseTransformPoint(handle),handEvent);hand.pinchValue.WriteValueIntoEvent(0f,handEvent);InputSystem.QueueEvent(handEvent);}InputSystem.Update();yield return null;
  using(StateEvent.From(hand,out var handEvent)){hand.pinchValue.WriteValueIntoEvent(1f,handEvent);hand.graspValue.WriteValueIntoEvent(1f,handEvent);InputSystem.QueueEvent(handEvent);}InputSystem.Update();yield return null;PackageReader.Require(player.MenuGrabbed,"Tracked hand pinch did not grab menu.");
  using(StateEvent.From(hand,out var handEvent)){hand.pointerPosition.WriteValueIntoEvent(space.InverseTransformPoint(start+Vector3.right*.25f),handEvent);hand.pinchPosition.WriteValueIntoEvent(space.InverseTransformPoint(handle+Vector3.right*.25f),handEvent);hand.pointerRotation.WriteValueIntoEvent(Quaternion.Inverse(space.rotation)*Quaternion.Euler(0,170,90)*grabRotation,handEvent);InputSystem.QueueEvent(handEvent);}InputSystem.Update();yield return null;PackageReader.Require(Vector3.Distance(menu.transform.position,menuStart+Vector3.right*.25f)<.01f,"Pinched hand did not move menu.");PackageReader.Require(Quaternion.Angle(menu.transform.rotation,grabRotation)<.01f,"Hand aim rotation turned panel backwards.");
  using(StateEvent.From(hand,out var handEvent)){hand.pinchValue.WriteValueIntoEvent(0f,handEvent);InputSystem.QueueEvent(handEvent);}InputSystem.Update();yield return null;PackageReader.Require(!player.MenuGrabbed,"Hand release did not release menu.");PackageReader.Require(String.Join(",",player.WorldButtons.Keys)==beforeHandButtons,"Hand drag release activated a button.");parked=menu.transform.position;
  using(StateEvent.From(hand,out var handEvent)){hand.pointerPosition.WriteValueIntoEvent(space.InverseTransformPoint(start+Vector3.right),handEvent);InputSystem.QueueEvent(handEvent);}InputSystem.Update();yield return null;PackageReader.Require(Vector3.Distance(parked,menu.transform.position)<.001f,"Released hand still moved menu.");var tapTarget=player.WorldButtons["tab-navigate"].position;using(StateEvent.From(hand,out var e)){hand.pointerPosition.WriteValueIntoEvent(space.InverseTransformPoint(tapTarget-menu.transform.forward*.2f),e);hand.pointerRotation.WriteValueIntoEvent(Quaternion.Inverse(space.rotation)*menu.transform.rotation,e);hand.pinchPosition.WriteValueIntoEvent(space.InverseTransformPoint(tapTarget),e);hand.pinchValue.WriteValueIntoEvent(1f,e);InputSystem.QueueEvent(e);}InputSystem.Update();yield return null;using(StateEvent.From(hand,out var e)){hand.pinchValue.WriteValueIntoEvent(0f,e);InputSystem.QueueEvent(e);}InputSystem.Update();yield return null;PackageReader.Require(player.WorldButtons.ContainsKey("reset-view"),"Stationary hand pinch did not activate the button.");
  player.ActivateWorldControl("tab-inspect");tapTarget=player.WorldButtons["tab-navigate"].position;
  using(StateEvent.From(hand,out var e)){hand.pointerPosition.WriteValueIntoEvent(space.InverseTransformPoint(tapTarget-menu.transform.forward*.2f),e);hand.pointerRotation.WriteValueIntoEvent(Quaternion.Inverse(space.rotation)*menu.transform.rotation,e);hand.pinchPosition.WriteValueIntoEvent(space.InverseTransformPoint(tapTarget),e);hand.pinchValue.WriteValueIntoEvent(1f,e);InputSystem.QueueEvent(e);}InputSystem.Update();yield return null;PackageReader.Require(player.MenuGrabbed,"Pre-focus hand gesture missing.");
  player.SendMessage("OnApplicationFocus",false);yield return null;PackageReader.Require(!player.MenuGrabbed,"Focus loss retained grab.");player.SendMessage("OnApplicationFocus",true);yield return null;PackageReader.Require(!player.MenuGrabbed,"Held pinch reacquired on focus return.");
  using(StateEvent.From(hand,out var e)){hand.pinchValue.WriteValueIntoEvent(0f,e);InputSystem.QueueEvent(e);}InputSystem.Update();yield return null;PackageReader.Require(!player.WorldButtons.ContainsKey("reset-view"),"Focus-cancelled gesture clicked on release.");
  using(StateEvent.From(hand,out var e)){hand.pinchValue.WriteValueIntoEvent(1f,e);InputSystem.QueueEvent(e);}InputSystem.Update();yield return null;PackageReader.Require(player.MenuGrabbed,"Neutral input did not rearm gesture.");
  using(StateEvent.From(hand,out var e)){hand.pointer.isTracked.WriteValueIntoEvent(0f,e);InputSystem.QueueEvent(e);}InputSystem.Update();yield return null;PackageReader.Require(!player.MenuGrabbed,"Tracking loss retained grab.");
  using(StateEvent.From(hand,out var e)){hand.pointer.isTracked.WriteValueIntoEvent(1f,e);InputSystem.QueueEvent(e);}InputSystem.Update();yield return null;PackageReader.Require(!player.MenuGrabbed,"Held pinch reacquired on tracking return.");
  using(StateEvent.From(hand,out var e)){hand.pinchValue.WriteValueIntoEvent(0f,e);InputSystem.QueueEvent(e);}InputSystem.Update();yield return null;PackageReader.Require(!player.WorldButtons.ContainsKey("reset-view"),"Tracking-cancelled gesture clicked on release.");InputSystem.RemoveDevice(hand);

  player.OpenFile(Path.Combine(directory,"presentation-browser.milzet-package.json"));yield return null;PackageReader.Require(player.WorldButtons.ContainsKey("play"),"Presentation did not open directly into playback.");player.SeekDemonstration(1);yield return null;
  var overlay=player.OverlayObjects.Values.First();var screen=GameObject.Find("Movable lesson display").transform;var marker=player.Markers.Values.First().transform;var markerLocal=marker.localPosition;var guideLocal=player.GuideCursor.transform.localPosition;PackageReader.Require(player.GuideCursor.transform.parent==screen && player.GuideLine.transform.parent==screen,"Guide is detached from display.");
  player.SetDisplayWidth(1.2f);PackageReader.Require(Mathf.Abs(screen.localScale.x-.3f)<.001f && Vector3.Distance(marker.localPosition,markerLocal)<.001f,"Display resize broke marker alignment.");PackageReader.Require(Vector3.Distance(player.GuideCursor.transform.localPosition,guideLocal)<.001f,"Resize changed guide anchoring.");player.SetDisplayWidth(9);PackageReader.Require(player.DisplayWidth==4,"Display size exceeded limit.");player.SetDisplayWidth(2.4f);
  var mover=InputSystem.AddDevice<OculusTouchControllerProfile.OculusTouchController>();InputSystem.SetDeviceUsage(mover,UnityEngine.InputSystem.CommonUsages.LeftHand);yield return null;
  foreach(var target in new[]{overlay.transform,screen}){var bar=target;var from=bar.position-bar.forward*.15f;var beforePanel=target.position;PackageReader.Require(player.PointerDistance(new Ray(from,bar.forward))>0 && player.PointerDistance(new Ray(from,bar.forward))<=.16f,"Pointer did not stop at or before panel surface: "+target.name);
   using(StateEvent.From(mover,out var e)){mover.pointerPosition.WriteValueIntoEvent(space.InverseTransformPoint(from),e);mover.pointerRotation.WriteValueIntoEvent(Quaternion.Inverse(space.rotation)*bar.rotation,e);mover.isTracked.WriteValueIntoEvent(1f,e);mover.gripPressed.WriteValueIntoEvent(0f,e);InputSystem.QueueEvent(e);}InputSystem.Update();yield return null;
   using(StateEvent.From(mover,out var e)){mover.gripPressed.WriteValueIntoEvent(1f,e);InputSystem.QueueEvent(e);}InputSystem.Update();yield return null;PackageReader.Require(player.MenuGrabbed,"Panel handle grab failed: "+target.name);
   using(StateEvent.From(mover,out var e)){mover.pointerPosition.WriteValueIntoEvent(space.InverseTransformPoint(from+Vector3.left*.35f),e);InputSystem.QueueEvent(e);}InputSystem.Update();yield return null;PackageReader.Require(Vector3.Distance(target.position,beforePanel+Vector3.left*.35f)<.01f,"Panel drag failed: "+target.name);
   using(StateEvent.From(mover,out var e)){mover.gripPressed.WriteValueIntoEvent(0f,e);InputSystem.QueueEvent(e);}InputSystem.Update();yield return null;PackageReader.Require(!player.MenuGrabbed,"Panel release failed.");}
  var overlayPose=overlay.transform.position;var displayPose=screen.position;player.OpenFile(Path.Combine(directory,"equirect360-browser.milzet-package.json"));yield return null;player.OpenFile(Path.Combine(directory,"presentation-browser.milzet-package.json"));yield return null;player.SeekDemonstration(1);yield return null;PackageReader.Require(Vector3.Distance(player.OverlayObjects.Values.First().transform.position,overlayPose)<.001f && Vector3.Distance(GameObject.Find("Movable lesson display").transform.position,displayPose)<.001f,"Reference/display pose lost on reopen.");InputSystem.RemoveDevice(mover);
  PackageReader.Require(player.Markers.Values.All(m=>m.GetComponent<SphereCollider>()!=null),"Hotspot sphere collider missing.");var menuRay=new Ray(menu.transform.position-menu.transform.forward*.2f,menu.transform.forward);PackageReader.Require(Mathf.Abs(player.PointerDistance(menuRay)-.2f)<.01f,"Pointer did not stop at menu surface.");
  var promptText=player.WorldControls.GetComponentsInChildren<TMP_Text>().First(t=>t.name=="Prompt");PackageReader.Require(promptText.overflowMode==TextOverflowModes.Page && promptText.textWrappingMode==TextWrappingModes.Normal,"Menu body must wrap and paginate.");foreach(var control in player.WorldButtons.Values){var corners=new Vector3[4];control.GetWorldCorners(corners);foreach(var corner in corners)PackageReader.Require(((RectTransform)menu.transform).rect.Contains(menu.transform.InverseTransformPoint(corner)),"Menu control exceeds panel bounds.");}
  var cameraRotation=player.ViewCamera.transform.rotation;player.ViewCamera.transform.LookAt(player.WorldControls.transform.position);StandaloneVerification.CaptureVisibleControls(player,Path.Combine(output,"ux-menu-rounded.png"));player.ViewCamera.transform.rotation=cameraRotation;
  var reference=player.OverlayObjects.Values.First();var referenceRect=(RectTransform)reference.transform;foreach(var child in reference.GetComponentsInChildren<RectTransform>()){if(child==referenceRect)continue;var corners=new Vector3[4];child.GetWorldCorners(corners);foreach(var corner in corners)PackageReader.Require(referenceRect.rect.Contains(referenceRect.InverseTransformPoint(corner)),"Reference element outside card: "+child.name);}
  var referenceCameraPose=new Pose(player.ViewCamera.transform.position,player.ViewCamera.transform.rotation);player.ViewCamera.transform.SetPositionAndRotation(reference.transform.position-reference.transform.forward*1.2f,reference.transform.rotation);typeof(StartupVerification).GetMethod("CaptureAnimation",System.Reflection.BindingFlags.Static|System.Reflection.BindingFlags.NonPublic).Invoke(null,new object[]{player.ViewCamera,Path.Combine(output,"reference-card-polished.png")});player.ViewCamera.transform.SetPositionAndRotation(referenceCameraPose.position,referenceCameraPose.rotation);
  bool exitRequested=false;player.ExitOverride=()=>exitRequested=true;player.SeekDemonstration(0);player.ToggleDemonstration();PackageReader.Require(player.WorldButtons.ContainsKey("exit"),"Exit App is not visible.");player.ActivateWorldControl("exit");PackageReader.Require(exitRequested && !player.DemoPlayback.Playing && !player.MenuGrabbed && player.Loaded!=null,"Exit failed to pause and preserve package.");player.ExitOverride=null;
  File.WriteAllText(Path.Combine(output,"xr-controls-verification.json"),"{\"passed\":true,\"playMode\":true,\"worldControlRay\":true,\"renderedWorldControls\":true,\"activityResponses\":true,\"physicalTextSizing\":true,\"trackedCameraBinding\":true,\"inputSource\":\"simulated XR HMD and Touch controller\",\"controllerAimBinding\":true,\"persistentRigAcrossFivePackages\":true,\"locomotion\":true,\"controllerGrabMoveRelease\":true,\"handPinchMoveRelease\":true,\"graspPinchArbitration\":true,\"handAimDoesNotFlipPanel\":true,\"focusTrackingNeutralRearm\":true,\"menuPoseAcrossPackagesAndTabs\":true,\"referenceAndDisplayGrab\":true,\"resizePreservesHotspots\":true,\"contentOpenPlayback\":true,\"pointerStopsAtPanel\":true,\"physicalControllers\":\"not tested\",\"headset\":\"not tested\"}");Debug.Log("MILZET_XR_CONTROLS_PASS");StartupVerification.StartCheck(player,output);
 }
}
}
