import React from 'react';
import {removeTargetReferences} from '../Shared/references.mjs';
import {activityKinds} from '../Shared/activities.mjs';
export function ActivityEditor({draft,edit}){
 function update(id,fields){edit(m=>Object.assign(m.activities.find(a=>a.id===id),fields));}
 return <section><h3>Scenario activities</h3><p>Activities run in their authored order within each phase. Responses go to the external host; grading keys and private rubrics are not included in playable packages.</p><button onClick={()=>edit(m=>{m.activities=m.activities||[];m.activities.push({id:'activity-'+crypto.randomUUID(),phase:m.phases[0].id,kind:'acknowledgement',prompt:'',choices:[],hint:'',maxHints:0,startTime:0,endTime:0,citation:''});})} disabled={(draft.activities||[]).length>=64}>Add activity</button>
 {(draft.activities||[]).map((a,i)=><details key={a.id} open><summary>Activity {i+1}: {a.kind}</summary><div className="composition-phases"><label>Phase<select aria-label={'Activity '+(i+1)+' phase'} value={a.phase} onChange={e=>update(a.id,{phase:e.target.value,...(e.target.value==='prove'?{hint:'',maxHints:0}:{})})}>{draft.phases.map(p=><option key={p.id}>{p.id}</option>)}</select></label><label>Kind<select aria-label={'Activity '+(i+1)+' kind'} value={a.kind} onChange={e=>update(a.id,{kind:e.target.value,choices:e.target.value==='quiz'?['Choice 1','Choice 2']:[]})}>{activityKinds.map(kind=><option key={kind}>{kind}</option>)}</select></label></div>
 <label>Prompt<textarea aria-label={'Activity '+(i+1)+' prompt'} value={a.prompt} maxLength={2000} onChange={e=>update(a.id,{prompt:e.target.value})}/></label>{a.kind==='quiz' && <label>Choices, one per line<textarea aria-label={'Activity '+(i+1)+' choices'} value={a.choices.join('\n')} onChange={e=>update(a.id,{choices:e.target.value.split('\n')})}/></label>}
 <label>Source or module citation<input aria-label={'Activity '+(i+1)+' citation'} value={a.citation} maxLength={500} onChange={e=>update(a.id,{citation:e.target.value})}/></label>
 {a.phase!=='prove' && <div className="composition-phases"><label>Hint<input aria-label={'Activity '+(i+1)+' hint'} value={a.hint} maxLength={1000} onChange={e=>update(a.id,{hint:e.target.value})}/></label><label>Hint budget<input aria-label={'Activity '+(i+1)+' hint budget'} type="number" min="0" max="3" value={a.maxHints} onChange={e=>update(a.id,{maxHints:Number(e.target.value)})}/></label></div>}
 <div className="composition-phases"><label>Clip start (seconds)<input aria-label={'Activity '+(i+1)+' start'} type="number" min="0" max="3600" value={a.startTime} onChange={e=>update(a.id,{startTime:Number(e.target.value)})}/></label><label>Clip end (0 = no end)<input aria-label={'Activity '+(i+1)+' end'} type="number" min="0" max="3600" value={a.endTime} onChange={e=>update(a.id,{endTime:Number(e.target.value)})}/></label></div>
 <div className="package-actions"><button disabled={i===0} onClick={()=>edit(m=>{[m.activities[i-1],m.activities[i]]=[m.activities[i],m.activities[i-1]];})}>Move activity up</button><button onClick={()=>edit(m=>{m.activities=m.activities.filter(x=>x.id!==a.id);removeTargetReferences(m,'activity',a.id);})}>Remove activity</button></div></details>)}
 </section>;
}
