import {checkPilotStructure} from '../Shared/pilot-checks.mjs';
import {pilotTypes} from '../Shared/context.mjs';
import React,{useEffect,useRef,useState} from 'react';
import {createExperience,openExperience,putExperienceScene,orderExperience,sealExperience,createJourney,MAX_EXPERIENCE_BYTES} from '../Shared/experience.mjs';
import {readExperience,writeExperience} from './experience-store.mjs';
export function ExperienceEditor({loaded,activate,sceneComplete,bridge}){
 const [pilot,setPilot]=useState(pilotTypes[1]),[report,setReport]=useState(null);
 const [experience,setExperience]=useState(null),[title,setTitle]=useState('Onsite experience'),[busy,setBusy]=useState(true),[message,setMessage]=useState(''),[events,setEvents]=useState([]),[release,setRelease]=useState(false),[playing,setPlaying]=useState(false),[done,setDone]=useState(false);
 const journey=useRef(null),granted=useRef(false);granted.current=release;
 useEffect(()=>{let live=true;readExperience().then(async e=>{if(e){const value=await openExperience(JSON.stringify(e));if(live){setExperience(value);setTitle(value.manifest.title);}}}).catch(e=>{if(live)setMessage(e.message);}).finally(()=>{if(live)setBusy(false);});return()=>{live=false;};},[]);
 async function work(fn){setBusy(true);setMessage('Saving experience…');try{await fn();}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 async function save(envelope){const next=await openExperience(JSON.stringify(envelope));await writeExperience(envelope);setExperience(next);setReport(null);setTitle(next.manifest.title);journey.current=null;setPlaying(false);setDone(false);setEvents([]);setMessage('Experience and all scene packages saved locally.');}
 async function editScene(id){journey.current=null;setPlaying(false);await activate(experience.packages.get(id).envelope);setMessage('Scene opened for editing. Apply composition, then Update current scene in experience.');}
 async function start(){setPlaying(false);setEvents([]);setRelease(false);setDone(false);await activate(experience.packages.get(experience.manifest.entryScene).envelope);journey.current=createJourney(experience,{sessionId:crypto.randomUUID(),authorize:async()=>granted.current,load:activate,emit:e=>setEvents(old=>[...old,e])});setPlaying(true);setMessage('Experience preview started. Complete each scene before continuing.');}
 const sameScene=!!experience?.packages.has(loaded?.manifest.id),currentMatches=playing && loaded?.envelope.manifestSha256===experience?.packages.get(journey.current?.sceneId)?.envelope.manifestSha256;
 async function advanceJourney(){if(!currentMatches || done)throw Error('Start the saved experience before continuing.');await journey.current.advance(sceneComplete);setDone(journey.current.complete);setRelease(false);setMessage(journey.current.complete?'Experience preview complete.':'Next scene opened.');}
 if(bridge)bridge.current=playing?{done,granted:release,advance:advanceJourney,toggleHost:()=>setRelease(value=>!value)}:null;
 return <details className="experience-editor"><summary>Multi-scene experience</summary><p>Combine saved scenes into an ordered package. Scene edits stay separate until you update their saved snapshot here. This preview starts fresh; real worker progress belongs to the host.</p><fieldset disabled={busy}><label>Experience title<input value={title} maxLength={120} onChange={e=>setTitle(e.target.value)}/></label><div className="package-actions"><button disabled={!loaded} onClick={()=>work(async()=>save(await createExperience(title,loaded.envelope)))}>Create experience from current scene</button><label className="button secondary">Open multi-scene experience<input hidden type="file" aria-label="Open multi-scene experience" accept=".json" onChange={e=>{const f=e.target.files?.[0];if(f)void work(async()=>{if(f.size>MAX_EXPERIENCE_BYTES)throw Error('Experience exceeds 120 MB.');const opened=await openExperience(await f.text());await save(opened.envelope);await activate(opened.packages.get(opened.manifest.entryScene).envelope);});e.target.value='';}}/></label></div>
 {experience && <><div className="package-actions"><button onClick={()=>work(async()=>save(await sealExperience({...experience.manifest,title:title.trim()})))}>Save experience title</button><button disabled={!loaded || sameScene || experience.manifest.scenes.length>=16} onClick={()=>work(async()=>save(await putExperienceScene(experience.envelope,loaded.envelope)))}>Add current scene to experience</button><button disabled={!sameScene} onClick={()=>work(async()=>save(await putExperienceScene(experience.envelope,loaded.envelope,true)))}>Update current scene in experience</button><button onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(experience.envelope)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=experience.manifest.id+'.milzet-experience.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Export experience + media</button></div>
 <ol>{experience.manifest.scenes.map((s,i)=>{const scene=experience.packages.get(s.id);return <li key={s.id}><strong>{scene.manifest.title}</strong><div className="package-actions"><button onClick={()=>work(()=>editScene(s.id))}>Edit scene {i+1}</button><button disabled={i===0} onClick={()=>work(async()=>{const order=experience.manifest.scenes.map(s=>s.id);[order[i-1],order[i]]=[order[i],order[i-1]];await save(await orderExperience(experience.envelope,order));})}>Move scene {i+1} earlier</button><button disabled={experience.manifest.scenes.length===1} onClick={()=>work(async()=>save(await orderExperience(experience.envelope,experience.manifest.scenes.filter(x=>x.id!==s.id).map(x=>x.id))))}>Remove scene {i+1}</button></div>{s.next && <label><input type="checkbox" aria-label={'Host release after scene '+(i+1)} checked={s.gate==='host'} onChange={e=>{const gate=e.target.checked?'host':'none',previous=experience,manifest={...experience.manifest,scenes:experience.manifest.scenes.map(x=>x.id===s.id?{...x,gate}:x)};setExperience({...experience,manifest});void work(async()=>{try{await save(await sealExperience(manifest));}catch(error){setExperience(previous);throw error;}});}}/>Require host release before next scene</label>}</li>;})}</ol>
 <label>Pilot structure check<select aria-label="Pilot structure check" value={pilot} onChange={e=>{setPilot(e.target.value);setReport(null);}}>{pilotTypes.filter(Boolean).map(p=><option key={p}>{p}</option>)}</select></label><button onClick={()=>setReport(checkPilotStructure(pilot,[...experience.packages.values()].map(p=>p.manifest)))}>Check pilot structure</button>{report && <section aria-label="Pilot structure results"><strong>{report.complete?'Required structure is present':'Structure still needs authoring'}</strong><ul>{report.requirements.map(r=><li key={r.label}>{r.passed?'Present':'Missing'}: {r.label}</li>)}</ul><p>{report.acceptance}</p></section>}<button onClick={()=>work(start)}>Start experience preview</button>{playing && <div><p>Scene {experience.manifest.scenes.findIndex(s=>s.id===journey.current?.sceneId)+1} of {experience.manifest.scenes.length}{done?' · complete':''}</p>{!currentMatches && <p>The current scene differs from this saved experience. Restart the experience preview to continue.</p>}<label><input aria-label="Simulate scene release" type="checkbox" checked={release} onChange={e=>setRelease(e.target.checked)}/>Simulate scene release (test host)</label><button disabled={!currentMatches || done} onClick={()=>work(async()=>{await journey.current.advance(sceneComplete);setDone(journey.current.complete);setRelease(false);setMessage(journey.current.complete?'Experience preview complete.':'Next scene opened.');})}>Continue experience</button></div>}<pre aria-label="Experience event log">{JSON.stringify(events,null,2)}</pre></>}
 </fieldset><p role="status">{message}</p></details>;
}
