import {imageDerivative} from './image-derivative.mjs';
import {attachLibraryProvenance} from '../Shared/provenance.mjs';
import {createImageScenario} from '../Shared/authoring.mjs';
import React,{useState,useEffect} from 'react';
import {emptyLibrary,validateLibrary,importSource,archiveRevision,prepareJob,prepareRefine} from '../Shared/library.mjs';
import {fromBase64} from '../Shared/package.mjs';
import {readLibrary,writeLibrary} from './library-store.mjs';
function download(data,name,type='application/json'){const url=URL.createObjectURL(new Blob([data],{type}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function SourceLibrary({loaded,activate}){
 const [copySize,setCopySize]=useState(2048);
 const [library,setLibrary]=useState(emptyLibrary),[busy,setBusy]=useState(true),[status,setStatus]=useState(''),[owner,setOwner]=useState(''),[license,setLicense]=useState(''),[credit,setCredit]=useState(''),[source,setSource]=useState(''),[provider,setProvider]=useState('elevenlabs'),[prompt,setPrompt]=useState(''),[voice,setVoice]=useState(''),[origin,setOrigin]=useState(''),[capture,setCapture]=useState(''),[parent,setParent]=useState(''),[rubric,setRubric]=useState('');
 useEffect(()=>{let alive=true;readLibrary().then(async saved=>{if(saved){await validateLibrary(saved);if(alive)setLibrary(saved);}}).catch(e=>{if(alive)setStatus(e.message);}).finally(()=>{if(alive)setBusy(false);});return()=>{alive=false;};},[]);
 async function save(work){setBusy(true);setStatus('Saving sources…');try{const next=await work();await validateLibrary(next);await writeLibrary(next);setLibrary(next);setStatus('Source library saved locally.');}catch(e){setStatus(e.message);}finally{setBusy(false);}}
 return <details className="source-library"><summary>Source library, revisions and generation requests</summary><p>Keep original client media, credits and usage rights with your project. Source backups include private authoring information; runtime packages remain separate.</p>
 <fieldset disabled={busy}><div className="composition-phases"><label>Content owner<input value={owner} onChange={e=>setOwner(e.target.value)}/></label><label>Usage rights or licence<input value={license} onChange={e=>setLicense(e.target.value)}/></label><label>Credit<input value={credit} onChange={e=>setCredit(e.target.value)}/></label><label>Source or capture reference<input value={source} onChange={e=>setSource(e.target.value)}/></label></div>
 <div className="composition-phases"><label>Capture date<input type="date" value={capture} onChange={e=>setCapture(e.target.value)}/></label><label>Generation receipt<select aria-label="Generation receipt" value={origin} onChange={e=>setOrigin(e.target.value)}><option value="">Manual import</option>{library.jobs.filter(j=>j.status==='succeeded').map(j=><option value={j.id} key={j.id}>{j.provider} · {j.id}</option>)}</select></label><label>Derived from source<select aria-label="Derived from source" value={parent} onChange={e=>setParent(e.target.value)}><option value="">Original source</option>{library.assets.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label></div><div className="package-actions"><label className="button secondary">Import original source<input aria-label="Import original source" type="file" hidden accept=".png,.jpg,.jpeg,.wav,.mp4,.glb" onChange={e=>{const f=e.target.files?.[0];if(f)void save(async()=>{if(f.size>12000000)throw Error('Source asset limit is 12 MB.');const mime=f.name.toLowerCase().endsWith('.glb')?'model/gltf-binary':f.name.toLowerCase().endsWith('.wav')?'audio/wav':f.type;return importSource(library,f.name,mime,new Uint8Array(await f.arrayBuffer()),{owner,license,credit,source,capturedAt:capture,provider:library.jobs.find(j=>j.id===origin)?.provider||'',jobId:origin,derivedFrom:parent});});e.target.value='';}}/></label>
 <button onClick={()=>download(JSON.stringify(library),'milzet-source-library.json')}>Back up source library</button><label className="button secondary">Restore source backup<input aria-label="Restore source backup" type="file" accept=".json" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void save(async()=>{if(f.size>120000000)throw Error('Source backup exceeds 120 MB.');return validateLibrary(JSON.parse(await f.text()));});e.target.value='';}}/></label>
 {loaded && <button onClick={()=>save(()=>archiveRevision(library,loaded.envelope))}>Archive current scenario revision</button>}{loaded && <button onClick={async()=>{try{await activate(await attachLibraryProvenance(loaded.envelope,library));}catch(e){setStatus(e.message);}}}>Attach source credits to package</button>}</div>
 <label>Optimized image copy size<select aria-label="Optimized image copy size" value={copySize} onChange={e=>setCopySize(Number(e.target.value))}>{[1024,2048,4096].map(size=><option key={size} value={size}>{size}px maximum edge</option>)}</select></label><p>JPEG copies keep the original source and its ownership record. Transparency becomes white; the source is never enlarged or overwritten.</p><div className="source-items">{library.assets.map(a=><article key={a.id}><strong>{a.name}</strong><p>{a.mime} · {a.bytes.toLocaleString()} bytes · {a.provenance.owner}<br/>{a.provenance.license} · {a.provenance.credit}</p><div className="package-actions"><button onClick={()=>download(fromBase64(a.base64),a.name,a.mime)}>Download original</button>{a.mime.startsWith('image/') && <button onClick={()=>save(async()=>{const bytes=await imageDerivative(fromBase64(a.base64),a.mime,copySize);return importSource(library,a.name.replace(/\.[^.]+$/,'')+'-'+copySize+'px.jpg','image/jpeg',bytes,{...a.provenance,derivedFrom:a.id});})}>Make optimized JPEG copy</button>}{a.mime.startsWith('image/') && <button onClick={async()=>{try{await activate(await attachLibraryProvenance(await createImageScenario(a.name,fromBase64(a.base64),a.mime),library));}catch(e){setStatus(e.message);}}}>Create scenario from this source</button>}</div><small>SHA-256 {a.sha256}</small></article>)}</div>
 {loaded && <details><summary>Private author rubric</summary><p>Keep assessor notes and answer keys here. They are included only in source backups and are never added to playable packages.</p><label>Private rubric text<textarea aria-label="Private rubric text" rows={5} maxLength={10000} value={rubric} onChange={e=>setRubric(e.target.value)}/></label><button onClick={()=>save(async()=>{if(!rubric.trim())throw Error('Enter rubric notes.');const next=structuredClone(library);next.rubrics=(next.rubrics||[]).filter(r=>r.revision!==loaded.envelope.manifestSha256);next.rubrics.push({revision:loaded.envelope.manifestSha256,title:loaded.manifest.title,text:rubric});return next;})}>Save private rubric</button>{(library.rubrics||[]).map(r=><details key={r.revision}><summary>{r.title} · {r.revision.slice(0,10)}</summary><p>{r.text}</p></details>)}</details>}<h3>Saved scenario revisions</h3>{library.revisions.map(r=><div className="package-actions" key={r.revision}><span>{JSON.parse(r.envelope.manifest).title} · {r.savedAt}</span><button onClick={()=>activate(r.envelope)}>Open archived revision</button></div>)}
 <label className="button secondary">Import worker job receipt<input aria-label="Import worker job receipt" type="file" accept=".json" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void save(async()=>{if(f.size>1000000)throw Error('Receipt exceeds 1 MB.');const receipt=JSON.parse(await f.text());const existing=library.jobs.find(j=>j.id===receipt.id);if(!existing || existing.provider!==receipt.provider || existing.prompt!==receipt.prompt || existing.voiceId!==receipt.voiceId || existing.stage!==receipt.stage || existing.parentJobId!==receipt.parentJobId || existing.previewRemoteId!==receipt.previewRemoteId)throw Error('Receipt does not match a prepared job.');const next=structuredClone(library);next.jobs=next.jobs.map(j=>j.id===receipt.id?receipt:j);return next;});e.target.value='';}}/></label><h3>Prepare generation</h3><p>Prepare a request for the local generation worker. Preparation uses no credits and sends no content. Review the request before authorizing a paid submission.</p><div className="composition-phases"><label>Provider<select aria-label="Generation provider" value={provider} onChange={e=>setProvider(e.target.value)}><option value="elevenlabs">ElevenLabs narration</option><option value="meshy">Meshy 3D preview</option></select></label>{provider==='elevenlabs' && <label>Verified voice ID<input value={voice} onChange={e=>setVoice(e.target.value)}/></label>}</div><label>Generation prompt<textarea value={prompt} maxLength={5000} rows={4} onChange={e=>setPrompt(e.target.value)}/></label><button onClick={()=>save(async()=>{const next=structuredClone(library);next.jobs.push(prepareJob(provider,prompt,voice));return next;})}>Prepare generation request</button>
 {library.jobs.map(j=><div className="package-actions" key={j.id}><span>{j.provider}{j.stage==='refine'?' texture refinement':''} · {j.status} · {j.prompt.slice(0,80)}</span><button onClick={()=>download(JSON.stringify(j,null,2),j.id+'.milzet-job.json')}>Export request</button>{j.provider==='meshy' && j.stage!=='refine' && j.status==='succeeded' && !library.jobs.some(child=>child.parentJobId===j.id) && <button onClick={()=>save(async()=>{const next=structuredClone(library);next.jobs.push(prepareRefine(j));return next;})}>Prepare texture refinement</button>}</div>)}
 </fieldset><p role="status">{status}</p></details>;
}
