import React from 'react';
import {emptyPresentation} from '../Shared/presentation.mjs';
export function PresentationEditor({draft,edit}){
 const value=draft.presentation||emptyPresentation(),demo=value.demonstration;
 const update=work=>edit(m=>{m.presentation=m.presentation||emptyPresentation();work(m.presentation);});
 const vector=(label,values,change)=> <div className="composition-phases">{values.map((v,i)=><label key={i}>{label} {'XYZ'[i]}<input aria-label={label+' '+'XYZ'[i]} type="number" step="0.1" value={v} onChange={e=>change(values.map((n,j)=>i===j?Number(e.target.value):n))}/></label>)}</div>;
 const phaseOptions=draft.phases.map(p=><option key={p.id} value={p.id}>{p.id}</option>);
 return <section className="presentation-editor"><h3>Overlays and demonstration</h3><p>Place diagrams, procedure text and other client references in metres (forward −Z). The guide moves through the scene while the viewer remains in control of their head position. Apply the composition to preview.</p>
 <button disabled={value.overlays.length>=16} onClick={()=>update(p=>p.overlays.push({id:'overlay-'+crypto.randomUUID(),kind:'label',text:'Client reference',imageAssetId:'',position:[0,1.8,-1.6],rotation:[0,0,0],size:[1.2,.5],phase:'',startTime:0,endTime:0,citation:''}))}>Add overlay</button>
 {value.overlays.map((o,i)=>{const change=fields=>update(p=>Object.assign(p.overlays[i],fields));return <details key={o.id} open><summary>Overlay {i+1}</summary><label>Overlay kind<select value={o.kind} onChange={e=>change({kind:e.target.value})}>{['label','diagram','sop','ppe','limits'].map(k=><option key={k}>{k}</option>)}</select></label><label>Overlay text<textarea aria-label={'Overlay text '+(i+1)} value={o.text} maxLength={1200} onChange={e=>change({text:e.target.value})}/></label><label>Overlay image<select aria-label={'Overlay image '+(i+1)} value={o.imageAssetId} onChange={e=>change({imageAssetId:e.target.value})}><option value="">Text only</option>{draft.assets.filter(a=>a.mime.startsWith('image/')).map(a=><option key={a.id} value={a.id}>{a.id}</option>)}</select></label>{vector('Overlay '+(i+1)+' position',o.position,position=>change({position}))}{vector('Overlay '+(i+1)+' rotation',o.rotation,rotation=>change({rotation}))}<label>Width (metres)<input aria-label={'Overlay width '+(i+1)} type="number" min="0.1" max="5" step="0.1" value={o.size[0]} onChange={e=>change({size:[Number(e.target.value),o.size[1]]})}/></label><label>Height (metres)<input aria-label={'Overlay height '+(i+1)} type="number" min="0.1" max="5" step="0.1" value={o.size[1]} onChange={e=>change({size:[o.size[0],Number(e.target.value)]})}/></label><label>Overlay phase<select aria-label={'Overlay phase '+(i+1)} value={o.phase} onChange={e=>change({phase:e.target.value})}><option value="">Every phase</option>{phaseOptions}</select></label>{['startTime','endTime'].map(k=><label key={k}>{k==='startTime'?'Show from (seconds)':'Show until (0 = always)'}<input aria-label={'Overlay '+(i+1)+' '+k} type="number" min="0" step="0.1" value={o[k]} onChange={e=>change({[k]:Number(e.target.value)})}/></label>)}<label>Overlay source reference<input aria-label={'Overlay citation '+(i+1)} maxLength={1000} value={o.citation} onChange={e=>change({citation:e.target.value})}/></label><button onClick={()=>update(p=>{p.overlays.splice(i,1);})}>Remove overlay {i+1}</button></details>;})}
 <label className="check-row"><input aria-label="Enable demonstration" type="checkbox" checked={!!demo} onChange={e=>update(p=>{p.demonstration=e.target.checked?{phase:draft.phases.find(p=>p.id==='shadow')?.id||draft.phases[0].id,duration:30,narrationAssetId:'',path:[],cues:[]}:null;if(!e.target.checked)p.overlays.forEach(o=>{o.startTime=0;o.endTime=0;});})}/>Enable timed demonstration</label>
 {demo && <><label>Demonstration phase<select aria-label="Demonstration phase" value={demo.phase} onChange={e=>update(p=>{p.demonstration.phase=e.target.value;})}>{phaseOptions}</select></label><label>Demonstration duration (seconds)<input aria-label="Demonstration duration" type="number" min="0.1" max="600" step="0.1" value={demo.duration} onChange={e=>update(p=>{p.demonstration.duration=Number(e.target.value);})}/></label><label>Demonstration narration<select aria-label="Demonstration narration" value={demo.narrationAssetId} onChange={e=>update(p=>{p.demonstration.narrationAssetId=e.target.value;})}><option value="">No narration</option>{draft.assets.filter(a=>a.mime==='audio/wav').map(a=><option key={a.id} value={a.id}>{a.id}</option>)}</select></label><p>Narration and the video plate follow demonstration time. Pause cues freeze both; seeking resets the clock. Keep the authored duration within the imported recording.</p>
 <button disabled={demo.path.length>=64} onClick={()=>update(p=>{const d=p.demonstration;if(!d.path.length)d.path=[{time:0,position:[-.5,1.5,-1]},{time:d.duration,position:[.5,1.5,-1]}];else d.path.push({time:d.duration,position:[0,1.5,-1]});})}>{demo.path.length?'Add guide point':'Add guide path'}</button>
 {demo.path.map((point,i)=><details key={i} open><summary>Guide point {i+1}</summary><label>Time (seconds)<input aria-label={'Guide time '+(i+1)} type="number" min="0" max={demo.duration} step="0.1" value={point.time} onChange={e=>update(p=>{p.demonstration.path[i].time=Number(e.target.value);})}/></label>{vector('Guide '+(i+1)+' position',point.position,position=>update(p=>{p.demonstration.path[i].position=position;}))}<button onClick={()=>update(p=>{p.demonstration.path.splice(i,1);})}>Remove guide point {i+1}</button></details>)}
 <button disabled={demo.cues.length>=32} onClick={()=>update(p=>p.demonstration.cues.push({id:'cue-'+crypto.randomUUID(),time:Math.min(demo.duration,(demo.cues.at(-1)?.time??-5)+5),hotspotId:'',text:'Client demonstration cue',pause:false}))}>Add demonstration cue</button>
 {demo.cues.map((cue,i)=><details key={cue.id} open><summary>Demonstration cue {i+1}</summary><label>Cue time (seconds)<input aria-label={'Cue time '+(i+1)} type="number" min="0" max={demo.duration} step="0.1" value={cue.time} onChange={e=>update(p=>{p.demonstration.cues[i].time=Number(e.target.value);})}/></label><label>Cue text<textarea aria-label={'Cue text '+(i+1)} value={cue.text} maxLength={1200} onChange={e=>update(p=>{p.demonstration.cues[i].text=e.target.value;})}/></label><label>Highlight hotspot<select aria-label={'Cue hotspot '+(i+1)} value={cue.hotspotId} onChange={e=>update(p=>{p.demonstration.cues[i].hotspotId=e.target.value;})}><option value="">No highlight</option>{draft.hotspots.filter(h=>draft.phases.find(p=>p.id===demo.phase)?.hotspotIds.includes(h.id)).map(h=><option key={h.id} value={h.id}>{h.label}</option>)}</select></label><label className="check-row"><input aria-label={'Pause at cue '+(i+1)} type="checkbox" checked={cue.pause} onChange={e=>update(p=>{p.demonstration.cues[i].pause=e.target.checked;})}/>Pause for inspection</label><button onClick={()=>update(p=>{p.demonstration.cues.splice(i,1);})}>Remove cue {i+1}</button></details>)}</>}
 </section>;
}
