import React,{useEffect,useRef,useState} from 'react';
import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {createImmersiveControls} from '../Shared/immersive-controls.mjs';
import {mountImmersivePanel} from './immersive-panel.mjs';
import {mountPresentation} from './presentation-scene.mjs';
import {anchor,surface} from '../Shared/projection.mjs';
export function Scene({loaded,onSelect,onTime,phase,controls}) {
 const controlsRef=useRef(controls),panelPreview=useRef(false);controlsRef.current=controls;
 const [showPanel,setShowPanel]=useState(false);panelPreview.current=showPanel;
 const phaseRef=useRef(phase),timeCallback=useRef(onTime),presentation=useRef(null);phaseRef.current=phase;timeCallback.current=onTime;
 const [demoState,setDemoState]=useState({time:0,playing:false,cue:'',overlayCount:0,highlight:'',guide:null});
 const mount=useRef(null), runtime=useRef(null), select=useRef(onSelect),video=useRef(null);select.current=onSelect;
 const [available,setAvailable]=useState(false),[error,setError]=useState(''),[duration,setDuration]=useState(0),[time,setTime]=useState(0);
 useEffect(()=>{
  let renderer;let stopped=false;let texture;let url;
  const resources=[];
  try {
   renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.xr.enabled=true;
   const immersive=loaded.manifest.plate.projection!=='flat';const scene=new T.Scene();scene.background=new T.Color('#152a27');const camera=new T.PerspectiveCamera(60,1,.1,100);camera.position.set(0,1.5,immersive?0:1);
   mount.current.appendChild(renderer.domElement);
   const asset=loaded.manifest.assets.find(a=>a.id===loaded.manifest.plate.assetId);
   url=URL.createObjectURL(new Blob([loaded.bytes.get(asset.id)],{type:asset.mime}));
   if(asset.mime==='video/mp4'){const media=document.createElement('video');media.src=url;media.playsInline=true;media.preload='auto';media.onloadedmetadata=()=>{const ratio=loaded.manifest.plate.projection==='equirect360'?2:1;if(immersive && media.videoWidth!==media.videoHeight*ratio){setError('Video dimensions do not match the selected mono projection.');media.removeAttribute('src');return;}setDuration(media.duration);};media.ontimeupdate=()=>{setTime(media.currentTime);if(loaded.manifest.presentation?.demonstration?.phase!==phaseRef.current && timeCallback.current?.(media.currentTime))media.pause();};media.onerror=()=>setError('The browser could not decode this video. Use H.264 MP4.');video.current=media;texture=new T.VideoTexture(media);}else{texture=new T.TextureLoader().load(url);}texture.colorSpace=T.SRGBColorSpace;
   const geometry=immersive?new T.BufferGeometry():new T.PlaneGeometry(4,2.4);if(immersive){const data=surface(loaded.manifest.plate.projection);geometry.setAttribute('position',new T.Float32BufferAttribute(data.positions,3));geometry.setAttribute('uv',new T.Float32BufferAttribute(data.uvs,2));geometry.setIndex(data.indices);geometry.computeVertexNormals();}const material=new T.MeshBasicMaterial({map:texture});resources.push(geometry,material);
   const plate=new T.Mesh(geometry,material);if(!immersive)plate.position.set(0,1.5,-2);scene.add(plate);
   const targets=loaded.manifest.hotspots.map(h=>{const g=new T.SphereGeometry(.065,16,12),m=new T.MeshBasicMaterial({color:'#d6f895'});resources.push(g,m);const mesh=new T.Mesh(g,m);mesh.position.set(...anchor(h.x,h.y,loaded.manifest.plate.projection));mesh.userData.id=h.id;scene.add(mesh);return mesh;});
   const markerMeshes=[...targets];presentation.current=mountPresentation(scene,loaded,markerMeshes,setError);
   scene.add(new T.HemisphereLight(0xffffff,0x667766,2));const sunlight=new T.DirectionalLight(0xffffff,3);sunlight.position.set(2,4,3);scene.add(sunlight);
   const objects=new Map();for(const o of loaded.manifest.objects||[]){const group=new T.Group();group.name=o.label;group.position.fromArray(o.position);group.rotation.set(...o.rotation.map(x=>x*Math.PI/180));group.scale.fromArray(o.scale);group.visible=o.visible;objects.set(o.id,group);}
   for(const o of loaded.manifest.objects||[]){const group=objects.get(o.id);(objects.get(o.parentId)||scene).add(group);const data=loaded.bytes.get(o.assetId);new GLTFLoader().parse(data.buffer.slice(data.byteOffset,data.byteOffset+data.byteLength),'',gltf=>{if(stopped){gltf.scene.traverse(x=>{x.geometry?.dispose();if(x.material){const materials=Array.isArray(x.material)?x.material:[x.material];materials.forEach(m=>m.dispose());}});return;}group.add(gltf.scene);gltf.scene.traverse(x=>{if(x.isMesh){resources.push(x.geometry);const materials=Array.isArray(x.material)?x.material:[x.material];for(const m of materials){resources.push(m);for(const value of Object.values(m))if(value?.isTexture)resources.push(value);}if(o.hotspotId){x.userData.id=o.hotspotId;targets.push(x);}}});},e=>{if(!stopped)setError('Model decode failed: '+e.message);});}
   const model=createImmersiveControls(()=>{const state=controlsRef.current.read(),demo=loaded.manifest.presentation?.demonstration,pb=presentation.current.playback,media=video.current;return {...state,media:demo?.phase===phaseRef.current?{description:'Demonstration · '+pb.time.toFixed(1)+' / '+demo.duration+' s',time:pb.time,duration:demo.duration,playing:pb.playing,enabled:phaseRef.current===demo.phase,toggle:()=>presentation.current.toggle(media),seek:t=>presentation.current.seek(t,media)}:media?{description:'Video · '+media.currentTime.toFixed(1)+' s',time:media.currentTime,duration:media.duration||0,playing:!media.paused,enabled:!!media.duration,toggle:()=>media.paused?media.play():media.pause(),seek:t=>{media.currentTime=t;}}:null};},{select:id=>controlsRef.current.select(id),advance:()=>controlsRef.current.advance(),respond:(id,r)=>controlsRef.current.respond(id,r),hint:id=>controlsRef.current.hint(id),audio:()=>controlsRef.current.audio(),toggleHost:()=>controlsRef.current.toggleHost(),exit:async()=>{const session=renderer.xr.getSession();if(session)await session.end();else{panelPreview.current=false;setShowPanel(false);}}});
   const panel=mountImmersivePanel(scene,model,setError);const ray=new T.Raycaster();
   function hitTarget(){const panelHit=panel.mesh.visible?ray.intersectObject(panel.mesh)[0]:null;if(panelHit){panel.select(panelHit);return;}const hit=ray.intersectObjects(targets.filter(t=>{let p=t;while(p){if(!p.visible)return false;p=p.parent;}return true;}))[0];if(hit)select.current(hit.object.userData.id);}

   let start=null,moved=false,yaw=0,pitch=0;
   const down=e=>{start={x:e.clientX,y:e.clientY,yaw,pitch};moved=false;};
   const move=e=>{if(!start || !immersive || renderer.xr.isPresenting)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;if(Math.abs(dx)+Math.abs(dy)>5)moved=true;yaw=start.yaw-dx*.005;pitch=Math.max(-Math.PI*.49,Math.min(Math.PI*.49,start.pitch-dy*.005));camera.rotation.set(pitch,yaw,0,'YXZ');};
   const click=e=>{start=null;if(moved)return;const b=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new T.Vector2((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1),camera);hitTarget();};
   renderer.domElement.addEventListener('pointerup',click);renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.style.touchAction='none';
   for(let i=0;i<2;i++){const controller=renderer.xr.getController(i);controller.addEventListener('select',()=>{ray.ray.origin.setFromMatrixPosition(controller.matrixWorld);ray.ray.direction.set(0,0,-1).transformDirection(controller.matrixWorld);hitTarget();});const lineGeometry=new T.BufferGeometry().setFromPoints([new T.Vector3(0,0,0),new T.Vector3(0,0,-4)]),lineMaterial=new T.LineBasicMaterial({color:0x99d9d2});resources.push(lineGeometry,lineMaterial);controller.add(new T.Line(lineGeometry,lineMaterial));scene.add(controller);}
   const observer=new ResizeObserver(()=>{if(!mount.current)return;const {width,height}=mount.current.getBoundingClientRect();renderer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix();});observer.observe(mount.current);
   renderer.setAnimationLoop(()=>{panel.update(renderer.xr.isPresenting || panelPreview.current,!renderer.xr.isPresenting);presentation.current?.update(phaseRef.current,video.current,state=>{setDemoState(state);if(loaded.manifest.presentation?.demonstration?.phase===phaseRef.current && timeCallback.current?.(state.time))presentation.current?.pause(video.current);});renderer.render(scene,camera);});runtime.current=renderer;
   navigator.xr?.isSessionSupported('immersive-vr').then(value=>{if(!stopped)setAvailable(value);}).catch(()=>{});
   return ()=>{stopped=true;panel.dispose();presentation.current?.dispose();presentation.current=null;observer.disconnect();renderer.domElement.removeEventListener('pointerup',click);renderer.domElement.removeEventListener('pointerdown',down);renderer.domElement.removeEventListener('pointermove',move);const session=renderer.xr.getSession();if(session)void session.end();renderer.setAnimationLoop(null);renderer.dispose();renderer.domElement.remove();if(video.current){video.current.pause();video.current.removeAttribute('src');video.current.load();video.current=null;}setDuration(0);setTime(0);texture?.dispose();resources.forEach(r=>r.dispose());URL.revokeObjectURL(url);runtime.current=null;};
  } catch(e){setError(e.message);renderer?.dispose();return ()=>{stopped=true;};}
 },[loaded]);
 return <div><div className="scene-view" ref={mount} aria-label="Package scene preview"/>{loaded.manifest.assets.find(a=>a.id===loaded.manifest.plate.assetId).mime==='video/mp4' && loaded.manifest.presentation?.demonstration?.phase!==phase && <div className="clip-controls"><button onClick={async()=>{try{if(video.current.paused)await video.current.play();else video.current.pause();}catch(e){setError(e.message);}}}>Play / pause clip</button><input aria-label="Clip time" type="range" min="0" max={duration||0} step="0.05" value={time} onChange={e=>{if(video.current)video.current.currentTime=Number(e.target.value);setTime(Number(e.target.value));}}/><output aria-label="Clip position">{time.toFixed(1)} / {duration.toFixed(1)} s</output></div>}{loaded.manifest.presentation && <div className="demonstration-controls"><output aria-label="Presentation visibility">{demoState.overlayCount} overlays visible</output>{loaded.manifest.presentation.demonstration && <><button disabled={phase!==loaded.manifest.presentation.demonstration.phase} onClick={async()=>{try{await presentation.current.toggle(video.current);}catch(e){setError(e.message);}}}>{demoState.playing?'Pause demonstration':'Play demonstration'}</button><input aria-label="Demonstration time" type="range" min="0" max={loaded.manifest.presentation.demonstration.duration} step="0.05" value={demoState.time} onChange={e=>presentation.current.seek(Number(e.target.value),video.current)}/><output aria-label="Demonstration position">{demoState.time.toFixed(1)} / {loaded.manifest.presentation.demonstration.duration.toFixed(1)} s</output>{demoState.narrationTime!==null && demoState.narrationTime!==undefined && <output aria-label="Demonstration narration position">{demoState.narrationTime.toFixed(1)} s · {demoState.narrationPlaying?'playing':'paused'}</output>}<p aria-label="Demonstration cue">{demoState.cue}</p><span aria-label="Demonstration highlight">{demoState.highlight}</span><span aria-label="Guide position">{demoState.guide?.map(x=>x.toFixed(2)).join(', ')}</span></>}</div>}{error && <p role="alert">{error}</p>}<button onClick={()=>setShowPanel(value=>!value)}>{showPanel?'Hide immersive controls':'Preview immersive controls'}</button><button disabled={!available} onClick={async()=>{try{const session=await navigator.xr.requestSession('immersive-vr');await runtime.current.xr.setSession(session);}catch(e){setError(e.message);}}}>Enter VR</button>{loaded.manifest.plate.projection!=='flat' && <p>Drag the preview to look around. The uncovered half of a 180° capture stays empty.</p>}<small className="xr-note">{available?'Immersive entry available; device acceptance pending.':'Desktop preview · immersive VR requires a compatible browser.'}</small></div>;
}
