const names={library:['milzetvrstudio.sources','library'],scene:['milzetvrstudio.packages','packages'],experience:['milzetvrstudio.experiences','experiences']};
function database(){return new Promise((resolve,reject)=>{const r=indexedDB.open('milzetvrstudio.workspace',2);r.onupgradeneeded=()=>{for(const name of ['state','projects'])if(!r.result.objectStoreNames.contains(name))r.result.createObjectStore(name);};r.onblocked=()=>reject(Error('Reload other studio tabs to update local storage.'));r.onsuccess=()=>{r.result.onversionchange=()=>r.result.close();resolve(r.result);};r.onerror=()=>reject(r.error);});}
async function legacy(key){if(key==='project'){try{return JSON.parse(localStorage.getItem('milzetvrstudio.draft.v1')||'null');}catch{return null;}}const [name,store]=names[key];return new Promise((resolve,reject)=>{const r=indexedDB.open(name,1);r.onupgradeneeded=()=>r.result.createObjectStore(store);r.onerror=()=>reject(r.error);r.onsuccess=()=>{const db=r.result,request=db.transaction(store).objectStore(store).get('current');request.onsuccess=()=>{resolve(request.result??null);db.close();};request.onerror=()=>{reject(request.error);db.close();};};});}
let identityPromise;
function identity(){if(!identityPromise)identityPromise=(async()=>{const db=await database();try{return await new Promise((resolve,reject)=>{let id;const tx=db.transaction('state','readwrite'),store=tx.objectStore('state'),r=store.get('workspaceId');r.onsuccess=()=>{id=r.result||crypto.randomUUID();if(!r.result)store.put(id,'workspaceId');};tx.oncomplete=()=>resolve(id);tx.onerror=()=>reject(tx.error);});}finally{db.close();}})();return identityPromise;}
export async function writeField(key,value){const expected=await identity(),db=await database();try{await new Promise((resolve,reject)=>{let failure;const tx=db.transaction('state','readwrite'),store=tx.objectStore('state'),r=store.get('workspaceId');r.onsuccess=()=>{if(r.result!==expected){failure=Error('The active client project changed. Reload this tab before saving.');tx.abort();}else store.put(value,key);};tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(failure||tx.error||Error('Workspace save aborted.'));});}finally{db.close();}}
export async function readField(key){await identity();const db=await database();let value;try{value=await new Promise((resolve,reject)=>{const r=db.transaction('state').objectStore('state').get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}finally{db.close();}if(value!==undefined)return value;const old=await legacy(key),next=await database();try{return await new Promise((resolve,reject)=>{let result;const tx=next.transaction('state','readwrite'),store=tx.objectStore('state'),request=store.get(key);request.onsuccess=()=>{result=request.result===undefined?old:request.result;if(request.result===undefined)store.put(old,key);};tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('Workspace migration aborted.'));});}finally{next.close();}}
export async function readWorkspace(){const keys=['project','library','scene','experience'];await Promise.all(keys.map(readField));const db=await database();try{return await new Promise((resolve,reject)=>{const value={},tx=db.transaction('state');for(const key of keys){const r=tx.objectStore('state').get(key);r.onsuccess=()=>{value[key]=r.result??null;};}tx.oncomplete=()=>resolve(value);tx.onerror=()=>reject(tx.error);});}finally{db.close();}}
const workspaceKeys=['project','library','scene','experience'];
function workspaceTitle(value){if(value.project?.title)return value.project.title;try{return JSON.parse(value.experience?.manifest||value.scene?.manifest||'{}').title||'Untitled client project';}catch{return 'Untitled client project';}}
export async function listWorkspaces(){const current=await readWorkspace(),id=await identity(),db=await database();try{return await new Promise((resolve,reject)=>{const tx=db.transaction('projects'),r=tx.objectStore('projects').getAll();r.onsuccess=()=>{const records=r.result.filter(p=>p.id!==id).map(p=>({id:p.id,title:p.title,current:false,updatedAt:p.updatedAt}));resolve([{id,title:workspaceTitle(current),current:true},...records]);};r.onerror=()=>reject(r.error);});}finally{db.close();}}
async function activateWorkspace(value,targetId){await readWorkspace();const expected=await identity(),db=await database();try{await new Promise((resolve,reject)=>{let failure;const tx=db.transaction(['state','projects'],'readwrite'),state=tx.objectStore('state'),projects=tx.objectStore('projects'),current={};for(const key of workspaceKeys){const r=state.get(key);r.onsuccess=()=>{current[key]=r.result??null;};}const active=state.get('workspaceId');active.onsuccess=()=>{if(active.result!==expected){failure=Error('The active client project changed. Reload this tab before switching.');tx.abort();return;}if(targetId===expected)return;
 const apply=(data,id)=>{if(workspaceKeys.some(k=>current[k]!==null))projects.put({id:expected,title:workspaceTitle(current),updatedAt:new Date().toISOString(),data:current},expected);for(const key of workspaceKeys)state.put(data[key],key);state.put(id,'workspaceId');};
 if(value)apply(value,crypto.randomUUID());else{const request=projects.get(targetId);request.onsuccess=()=>{if(!request.result){failure=Error('Client project is unavailable.');tx.abort();}else apply(request.result.data,targetId);};}};tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(failure||tx.error||Error('Project switch aborted.'));});}finally{db.close();}}
export const restoreWorkspace=value=>activateWorkspace(value,null);
export const switchWorkspace=id=>activateWorkspace(null,id);
